openapi: 3.0.3

servers:
  - url: http://localhost:4550/

info:
  description: Opal Fines Service - Defendant Account
  version: v0.0.1
  title: Opal Fines Service

paths:
  /defendant-accounts/{id}:
    patch:
      tags:
        - Defendant Account
      summary: Update Defendant Account
      description: Partially updates a Defendant Account by providing one group of attributes.
      operationId: updateDefendantAccount
      security:
        - permissions:
            - Account Maintenance (in the same business unit)
      parameters:
        - in: path
          name: id
          description: DB Mapping - defendant_accounts.defendant_account_id
          schema:
            type: integer
            format: int64
          required: true
        - in: header
          name: Authorization
          description: Bearer token
          schema:
            type: string
          required: false
        - in: header
          name: Business-Unit-Id
          description: Business Unit ID. DB Mapping - business_units.business_unit_id
          schema:
            type: string
          required: true
        - in: header
          name: If-Match
          description: Version of the defendant account. DB Mapping - defendant_accounts.account_version
          schema:
            $ref: "./types.yaml#/components/schemas/BigInt"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDefendantAccountRequest'
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateDefendantAccountResponse'
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        404:
          description: Not found
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        408:
          description: Request timeout
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
  /defendant-accounts/{id}/enforcement-status:
    get:
      tags:
        - Defendant Account
      summary: Get Defendant Account Enforcement Status
      description: The Get Defendant Account Enforcement Status API will be used to return the enforcement related information relating to a defendant account.
      operationId: getEnforcementStatus
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          description: DB Mapping - defendant_accounts.defendant_account_id
          schema:
            type: integer
            format: int64
          required: true
        - in: header
          name: Authorization
          description: Bearer token
          schema:
            type: string
          required: false
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                title: Get Enforcement Status Response
                type: object
                x-extendable: true
                additionalProperties: false
                properties:
                  enforcement_overview:
                    $ref: '#/components/schemas/enforcementOverview'
                  enforcement_override:
                    $ref: './common.yaml#/components/schemas/enforcementOverride'
                  last_enforcement_action:
                    $ref: '#/components/schemas/enforcementAction'
                  next_enforcement_action_data:
                    type: string
                    pattern: '^(?i:all|[A-Za-z0-9]{1,6}(,[A-Za-z0-9]{1,6})*|)$'
                    description: 'A comma-separated list of result IDs, ''all'' , or null .'
                  defendant_account_type:
                    type: string
                    enum:
                      - adult
                      - company
                      - youth
                  account_status_reference:
                    $ref: './common.yaml#/components/schemas/accountStatusReference'
                  employer_flag:
                    type: boolean
                  is_hmrc_check_eligible:
                    type: boolean
                    description: |
                      This field will return true if all of the following are met, else will return false.
                      - The defendant account has a date of birth
                      - The defendant account has a national insurance number
                      - The defendant account has a first name
                      - The defendant account has a last name
                      - The defendant account does not have zero balance
                      - The defendant account type is not one of the following
                      -- Company 
                      -- Youth
                      -- Parent / guardian to pay
                required:
                  - enforcement_overview
                  - defendant_account_type
                  - account_status_reference
                  - employer_flag
                  - is_hmrc_check_eligible

        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
  /defendant-accounts/{id}/header-summary-openapi-autogenerated-version:
    get:
      tags:
        - Defendant Account
      summary: Get Defendant Account Header Summary
      description: Returns a Header Summary for a Defendant Account.
      operationId: getDefendantAccountHeaderSummary
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          description: DB Mapping - defendant_accounts.defendant_account_id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                required:
                  - defendant_account_id
                  - account_number
                  - defendant_party_id
                  - debtor_type
                  - is_youth
                  - has_consolidated_accounts
                  - account_status_reference
                  - account_type
                  - originator_type
                  - originator_name
                  - business_unit_summary
                  - payment_state_summary
                  - party_details
                properties:
                  defendant_account_id:
                    type: string
                    description: DB Mapping - defendant_accounts.defendant_account_id
                  account_number:
                    type: string
                    description: DB Mapping - defendant_accounts.account_number
                  defendant_party_id:
                    type: string
                    description: defendant_account_parties.defendant_account_party_id (where defendant_account_parties.association_type = 'Defendant')
                  parent_guardian_party_id:
                    type: string
                    description: |
                      Only provided if a parent/guardian has been associated with the account, during account creation.
                      DB Mapping - defendant_account_parties.defendant_account_party_id (where defendant_account_parties.association_type = 'Parent/Guardian')
                  debtor_type:
                    type: string
                    enum:
                      - Defendant
                      - Parent/Guardian
                    description: |
                      This field will be set to 'Defendant' if defendant_account_parties.debtor = 'TRUE', otherwise if this is null and a Parent/Guardian is on the account with defendant_account_parties.debtor = 'TRUE', then the value returned is 'Parent/Guardian'.
                      DB Mapping - defendant_account_parties.debtor (where debtor = True)
                  is_youth:
                    type: boolean
                    description: |
                      DERIVED FROM THE DEFENDANT
                      The BE will need to check the defendants DOB via (parties.birth_date) and if:
                      parties.birth_date ≥ 18, then value is FALSE
                      I.e. An Adult defendant
                      parties.birth_date < 18, then value is TRUE
                      I.e. A Youth defendant
                      If parties.birth_date = null, then the defendants age (parties.age) should be observed:
                      parties.age ≥ 18, then the value is ‘FALSE’
                      parties.age < 18, then the value is ‘TRUE’
                      parties.age = null, then the value is ‘FALSE’

                      DB Mapping - parties.birth_date The defendants DOB is derived from this database field, but is not returned. Instead the BE will set the is_youth flag depending on the DOB value parties.age
                  has_consolidated_accounts:
                    type: boolean
                    description: This field will return true if the account has had accounts consolidated into it or false if it has not.
                  account_status_reference:
                    $ref: './common.yaml#/components/schemas/accountStatusReference'
                  account_type:
                    type: string
                    description: DB Mapping - defendant_accounts.account_type
                    enum:
                      - Fine
                      - Conditional Caution
                      - Confiscation
                      - Fixed Penalty
                  originator_type:
                    type: string
                    description: NEW - DB Mapping - defendant_accounts.originator_type
                    enum:
                      - TFO
                      - FP
                      - CASE
                      - MAC
                  originator_name:
                    type: string
                    description: NEW - DB Mapping - defendant.accounts.originator_name
                  prosecutor_case_reference:
                    type: string
                    description: DB Mapping - defendant.accounts.prosecutor_case_reference
                  fixed_penalty_ticket_number:
                    type: string
                    description: |
                      Only provided for Fixed Penalty accounts
                      DB Mapping - fixed_penalty_offences.ticket_number
                  business_unit_summary:
                    $ref: './common.yaml#/components/schemas/businessUnitSummary'
                  payment_state_summary:
                    $ref: './common.yaml#/components/schemas/paymentStateSummary'
                  party_details:
                    $ref: './common.yaml#/components/schemas/partyDetails'
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
  /defendant-accounts/{id}/impositions:
    get:
      tags:
        - Defendant Account
      summary: Get Defendant Account Impositions
      description: The Get Defendant Account Impositions API is used return an array of data relating to impositions on a defendant account, which populates the on screen table.
      operationId: getDefendantAccountImpositions
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          description: DB Mapping - defendant_accounts.defendant_account_id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/impositionSummary'

        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
components:
  schemas:
    updateDefendantAccountRequest:
      type: object
      additionalProperties: false
      oneOf:
        - required:
            - comment_and_notes
        - required:
            - enforcement_court
        - required:
            - collection_order
        - required:
            - enforcement_override
      properties:
        comment_and_notes:
          $ref: './common.yaml#/components/schemas/commentsAndNotes'
        enforcement_court:
          $ref: '#/components/schemas/enforcementCourtUpdate'
        collection_order:
          $ref: '#/components/schemas/collectionOrderUpdate'
        enforcement_override:
          $ref: '#/components/schemas/enforcementOverrideUpdate'
    updateDefendantAccountResponse:
      type: object
      additionalProperties: false
      oneOf:
        - required:
            - id
            - comment_and_notes
        - required:
            - id
            - enforcement_court
        - required:
            - id
            - collection_order
        - required:
            - id
            - enforcement_override
      properties:
        id:
          $ref: "./types.yaml#/components/schemas/BigInt"
        comment_and_notes:
          $ref: './common.yaml#/components/schemas/commentsAndNotes'
        enforcement_court:
          $ref: '#/components/schemas/enforcementCourtUpdate'
        collection_order:
          $ref: '#/components/schemas/collectionOrderUpdate'
        enforcement_override:
          $ref: '#/components/schemas/enforcementOverrideUpdate'
    enforcementCourtUpdate:
      type: object
      additionalProperties: false
      properties:
        enforcing_court_id:
          type: integer
          format: int64
        court_name:
          type: string
      required:
        - enforcing_court_id
    collectionOrderUpdate:
      type: object
      additionalProperties: false
      properties:
        collection_order:
          type: boolean
        collection_order_date:
          type: string
          format: date
      required:
        - collection_order
    enforcementOverrideUpdate:
      type: object
      additionalProperties: false
      properties:
        enf_override_result_id:
          type: string
        enf_override_enforcer_id:
          type: integer
          format: int64
        enf_override_tfo_lja_id:
          type: integer
    enforcementOverview:
      type: object
      additionalProperties: false
      properties:
        collection_order:
          $ref: './common.yaml#/components/schemas/collectionOrder'
        days_in_default:
          type: integer
        enforcement_court:
          $ref: './common.yaml#/components/schemas/courtReference'
      required:
        - collection_order
        - enforcement_court
    enforcementAction:
      type: object
      additionalProperties: false
      properties:
        enforcement_action:
          $ref: './common.yaml#/components/schemas/resultReference'
        reason:
          type: string
        enforcer:
          $ref: './common.yaml#/components/schemas/enforcerReference'
        warrant_number:
          type: string
        date_added:
          type: string
          format: date-time
        result_responses:
          type: array
          items:
            $ref: './common.yaml#/components/schemas/resultResponses'
      required:
        - enforcement_action
        - date_added
