openapi: 3.1.1

servers:
  - url: http://localhost:4550/

info:
  description: Opal Fines Service - Major Creditor
  version: v0.0.1
  title: Opal Fines Service

paths:
  /central-funds/{id}:
    get:
      tags:
        - Major Creditor
      summary: Get central fund by business unit
      operationId: getCentralFundByBusinessUnit
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          description: Business Unit ID. DB Mapping - configuration_items.business_unit_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                required:
                  - business_unit_details
                  - major_creditor
                properties:
                  major_creditor:
                    type: object
                    required:
                      - creditor_account_id
                      - account_number
                      - name
                    properties:
                      creditor_account_id:
                        type: integer
                        format: int64
                        description: The unique identifier for the major creditor account. DB Mapping from creditor_accounts.creditor_account_id
                      account_number:
                        type: string
                        description: The account number of the major creditor account. DB Mapping from creditor_accounts.account_number
                        minLength: 8
                        maxLength: 9
                      name:
                        type: string
                        description: DB Mapping configuration_items.item_values.$.name
                  business_unit_details:
                    $ref: './common.yaml#/components/schemas/businessUnitSummary'
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'


  /major-creditor-accounts/{id}/header-summary:
    get:
      tags:
        - Major Creditor
      summary: Returns a Header Summary for a Major Creditor Account.
      operationId: getMajorCreditorAccountHeaderSummary
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          description: DB Mapping - creditor_accounts.creditor_account_id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                required:
                  - business_unit_details
                  - major_creditor
                properties:
                  major_creditor:
                    type: object
                    required:
                      - creditor_account_id
                      - account_number
                      - name
                      - account_reference
                    properties:
                      creditor_account_id:
                        type: integer
                        format: int64
                        description: The unique identifier for the major creditor account. DB Mapping from creditor_accounts.creditor_account_id
                      account_number:
                        type: string
                        description: The account number of the major creditor account. DB Mapping from creditor_accounts.account_number
                        minLength: 8
                        maxLength: 9
                      name:
                        type: string
                        description: major_creditors.name where the creditor account type is 'MJ'  configuration_items.item_values.$.name where configuration_items.item_name = 'CENTRAL_FUND_ACCOUNT' and configuration_items.business_unit_id = creditor_accounts.business_unit_id
                      account_reference:
                        $ref: './common.yaml#/components/schemas/creditorAccountTypeReference'
                        description: Set to 'Major creditor' or 'Central fund'
                  awaiting_payout:
                    $ref: './types.yaml#/components/schemas/monetaryZeroOrPositive'
                    description: This is the sum of all payment transactions that have been paid by the defendants which has not been paid out to the major creditor. So transaction_amount in creditor_transactions that are related to the major creditor where payment_processed is FALSE and transaction_type = 'PAYMNT'
                  business_unit_details:
                    $ref: './common.yaml#/components/schemas/businessUnitSummary'

        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
  /major-creditor-accounts/{id}/at-a-glance:
    get:
      tags:
        - Major Creditor
      summary: Returns the At a glance information for Major creditors
      operationId: getMajorCreditorAccountAtAGlance
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          description: DB Mapping - creditor_accounts.creditor_account_id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                required:
                  - major_creditor
                properties:
                  major_creditor:
                    type: object
                    required:
                      - creditor_account_id
                      - name
                    properties:
                      creditor_account_id:
                        type: integer
                        format: int64
                        description: The unique identifier for the major creditor account. DB Mapping from creditor_accounts.creditor_account_id
                      name:
                        type: string
                        description: major_creditors.name where the creditor account type is 'MJ'  configuration_items.item_values.$.name where configuration_items.item_name = 'CENTRAL_FUND_ACCOUNT' and configuration_items.business_unit_id = creditor_accounts.business_unit_id. DB Mapping - $.major_creditor.name
                      code:
                        type: string
                        description: Required where creditor account type is 'MJ'. DB Mapping - $.major_creditor.code
                      address:
                        $ref: "./common.yaml#/components/schemas/majorCreditorAddressDetails"
                      pay_by_bacs:
                        type: boolean
                        description: Required where creditor account type is 'MJ' - DB Mapping - creditor_accounts.pay_by_bacs

        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
components:
  securitySchemes:
    permissions:
      type: http
      scheme: bearer
      bearerFormat: JWT
