openapi: 3.1.1

servers:
  - url: http://localhost:4550/

info:
  description: Opal Fines Service - Minor Creditor
  version: v0.0.1
  title: Opal Fines Service

paths:
  /minor-creditor-accounts/{id}:
    get:
      tags:
        - Minor Creditor
      summary: Get Minor Creditor Account
      description: The Get Minor Creditor Account will be used to return the low level data associated to the minor creditor account - such as personal details for the minor creditor, and payment details.
      operationId: getMinorCreditorAccount
      parameters:
        - in: path
          name: id
          description: DB Mapping - creditor_accounts.creditor_account_id
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: Version of the minor creditor account. DB Mapping - creditor_accounts.version
              schema:
                $ref: "./types.yaml#/components/schemas/BigInt"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/minorCreditorAccountResponse"
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
    patch:
      tags:
        - Minor Creditor
      summary: Update Minor Creditor Account
      description: The Update Minor Creditor Account will be used to update individual attributes of a Minor Creditor Account.
      operationId: patchMinorCreditorAccount
      parameters:
        - in: path
          name: id
          description: DB Mapping - creditor_accounts.creditor_account_id
          schema:
            type: integer
            format: int64
          required: true
        - in: header
          name: If-Match
          description: Version of the minor creditor account. DB Mapping - creditor_accounts.version
          schema:
            type: string
        - in: header
          name: Authorization
          description: Bearer token
          schema:
            type: string
          required: false
        - in: header
          name: Business-Unit-Id
          description: Business unit identifier
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              type: object
              required:
                - party_details
                - address
                - payment
              properties:
                party_details:
                  $ref: './common.yaml#/components/schemas/partyDetails'
                address:
                  $ref: './common.yaml#/components/schemas/addressDetails'
                payment:
                  $ref: './common.yaml#/components/schemas/creditorAccountPaymentDetails'
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: Version of the minor creditor account. DB Mapping - creditor_accounts.version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/minorCreditorAccountResponse"
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        404:
          description: Not found
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        408:
          description: Request timeout
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        409:
          description: Conflict
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'

  /minor-creditor-accounts/{id}/history:
    get:
      tags:
        - Minor Creditor
      summary: Get Minor Creditor History
      description: The Get Minor Creditor History API will be used to return history items, representing a chronology of activity on the account - ordered from latest to oldest.
      operationId: getMinorCreditorHistory
      security:
        - permissions:
            - Search and View Accounts (in at least one business unit)
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
        - in: query
          name: dateFrom
          description: Optional date parameter to filter history items from a specific date.
          schema:
            type: string
            format: date
        - in: query
          name: dateTo
          description: Optional date parameter to filter history items up to a specific date.
          schema:
            type: string
            format: date
        - in: query
          name: itemTypes
          description: Optional comma-separated list of history item types to filter by.
          schema:
            type: array
            items:
              type: string
              enum:
                - amendment
                - financial
                - note
            style: form
            explode: false
        - in: header
          name: Authorization
          description: Bearer token
          schema:
            type: string
          required: false
      responses:
        '200':
          description: OK
          headers:
            ETag:
              $ref: './common.yaml#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                properties:
                  historyItems:
                    type: array
                    items:
                      $ref: './history.yaml#/components/schemas/minorCreditorHistoryItem'
        400:
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        401:
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        403:
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        500:
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        503:
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
components:
  schemas:
    minorCreditorAccountResponse:
      additionalProperties: false
      type: object
      required:
        - creditor_account_id
        - party_details
        - address
        - payment
      properties:
        creditor_account_id:
          $ref: "./types.yaml#/components/schemas/BigInt"
        party_details:
          $ref: './common.yaml#/components/schemas/partyDetails'
        address:
          $ref: './common.yaml#/components/schemas/addressDetails'
        payment:
          allOf:
            - $ref: './common.yaml#/components/schemas/creditorAccountPaymentDetails'
            - properties:
                hold_payment:
                  type: boolean
                  description: DB Mapping - creditor_accounts.hold_payout
              required:
                - hold_payment
