openapi: 3.1.1

servers:
  - url: http://localhost:4550/

info:
  description: Opal Fines Service - Tills
  version: v0.0.1
  title: Opal Fines Service

paths:
  /tills:
    get:
      tags:
        - tills
      summary: Get tills
      operationId: get_tills
      description: Get list of tills filtered by business unit, status and auto-payments
      security:
        - permissions:
            - Process and Allocate Payments in (in the retrieved business unit)
      parameters:
        - in: query
          name: statuses
          schema:
            type: array
            minItems: 1
            items:
              type: string
              enum: [ CREATED, PROCESSING, FAILED, ALLOCATED ]
        - in: query
          name: auto_payments
          schema:
            type: boolean
        - in: query
          name: business_unit_ids
          schema:
            type: array
            minItems: 1
            items:
              type: integer
              format: int16
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TillsResponse'

        "400":
          description: Bad request
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        "401":
          description: Unauthorized
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        "403":
          description: Forbidden
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        "500":
          description: Internal server error
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'
        "503":
          description: Service unavailable
          content:
            application/json+problem:
              schema:
                $ref: './common.yaml#/components/schemas/ProblemDetail'

components:
  schemas:
    TillsResponse:
      type: object
      required:
        - tills
      properties:
        tills:
          type: array
          items:
            $ref: '#/components/schemas/Till'
    Till:
      type: object
      required:
        - till_number
        - errors
        - amount
        - business_unit_name
        - processed_by
      properties:
        till_number:
          type: integer
          format: int16
        errors:
          type: integer
        file_name:
          type: string
        source:
          type: string
        amount:
          type: number
          multipleOf: 0.01
        business_unit_name:
          type: string
        processed_by:
          type: string
        date_processed:
          type: string
          format: date