openapi: 3.1.1
info:
  description: Opal Fines Service - Types
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  title: Opal Fines Service
  version: v0.0.1
components:
  schemas:
    BigInt:
      type: integer
      format: int64
    monetaryZeroOrPositive:
      type: number
      description: A monetary value that is zero or positive, with up to two decimal places.
      maximum: 999999999999
      minimum: 0
      multipleOf: 0.01
