/**
* CGI OPAL Program
*
* MODULE      : load_business_units_ref_data.sql
*
* DESCRIPTION : The insert statements generated from the Legacy GoB system test Oracle database for the Business Units in that environment for use to populate the business_units table in the OPAL
*               Only Business Units for Fines and Confiscation are included here. So no Reciprocal Maintenance ones.
*
* VERSION HISTORY:
*
* Date          Author      Version     Nature of Change
* ----------    -------     --------    ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* 10/09/2024    A Dennis    1.0         PO-755 The insert statements generated from the Legacy GoB system test Oracle database for the Business Units in that environment for use to populate the business_units table in the OPAL
*                                       Only Business Units for Fines and Confiscation are included here. So no Reciprocal Maintenance ones.
*
**/
INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (2001,'Greater London','Area','01',NULL,NULL,'Confiscation',NULL);                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1001,'Greater London','Area','01',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1002,'Cumbria','Area','03',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1003,'Lancashire','Area','04',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1004,'Merseyside','Area','05',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (2005,'Greater Manchester','Area','06',NULL,NULL,'Confiscation',NULL);                                                                                                                                                                                                                                                                                                          

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1005,'Greater Manchester','Area','06',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1006,'Cheshire','Area','07',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (2007,'Northumbria','Area','10',NULL,NULL,'Confiscation',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1007,'Northumbria','Area','10',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1008,'Durham','Area','11',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1009,'North Yorkshire','Area','12',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                    

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1010,'West Yorkshire','Area','13',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                     

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1011,'South Yorkshire','Area','14',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                    

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1012,'Humberside','Area','16',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1013,'Cleveland','Area','17',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                          

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1014,'West Midlands','Area','20',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                      

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1015,'Staffordshire','Area','21',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                      

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1016,'West Mercia','Area','22',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1017,'Warwickshire','Area','23',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                       

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1018,'Derbyshire','Area','30',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1019,'Nottinghamshire','Area','31',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                    

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1020,'Lincolnshire','Area','32',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                       

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1021,'Leicestershire','Area','33',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                     

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1022,'Northamptonshire','Area','34',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1023,'Cambridgeshire','Area','35',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                     

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1024,'Norfolk','Area','36',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1025,'Suffolk','Area','37',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1026,'Bedfordshire','Area','40',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                       

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1027,'Hertfordshire','Area','41',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                      

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1028,'Essex','Area','42',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1029,'Thames Valley','Area','43',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                      

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1030,'Hampshire and Isle of Wight','Area','44',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1031,'Surrey','Area','45',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (2032,'Kent','Area','46',NULL,NULL,'Confiscation',NULL);                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1032,'Kent','Area','46',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                               

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1033,'Sussex','Area','47',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                             
INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1034,'Devon and Cornwall','Area','50',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (2035,'Avon and Somerset','Area','52',NULL,NULL,'Confiscation',NULL);                                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1035,'Avon and Somerset','Area','52',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1036,'Gloucestershire','Area','53',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                    

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1037,'Wiltshire','Area','54',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                          

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1038,'Dorset','Area','55',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1039,'North Wales','Area','60',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1040,'Gwent','Area','61',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1041,'South Wales','Area','62',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
            VALUES (1042,'Dyfed Powys','Area','63',NULL,NULL,'Fines',NULL);                                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (10,'Derbyshire','Accounting Division','0013',NULL,1018,'Fines',NULL);                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (103,'Pennine','Accounting Division','0080',NULL,1003,'Fines',NULL);                                                                                                                                                                                                                                                                                                                

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (105,'Liverpool','Accounting Division','0090',NULL,1004,'Fines',NULL);                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (106,'North Wales','Accounting Division','0094',NULL,1039,'Fines',TRUE);                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (11,'Dorset','Accounting Division','0020',NULL,1038,'Fines',NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (112,'Newcastle & Gateshead','Accounting Division','0103',NULL,1007,'Fines',NULL);                                                                                                                                                                                                                                                                                                  

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (119,'Nottingham','Accounting Division','0110',NULL,1019,'Fines',NULL);                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (12,'Durham','Accounting Division','0021',NULL,1008,'Fines',NULL);                                                                                                                                                                                                                                                                                                                  

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (124,'Sheffield','Accounting Division','0117',NULL,1011,'Fines',NULL);                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (125,'Surrey','Accounting Division','0122',NULL,1031,'Fines',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (126,'East  Sussex','Accounting Division','0123',NULL,1033,'Fines',NULL);                                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (128,'Warwickshire','Accounting Division','0128',NULL,1017,'Fines',NULL);                                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (129,'West Mercia','Accounting Division','0129',NULL,1016,'Fines',NULL);                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (130,'Birmingham & Sutton','Accounting Division','0130',NULL,1014,'Fines',NULL);                                                                                                                                                                                                                                                                                                    

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (135,'Bradford, Keighley & Halifax','Accounting Division','0135',NULL,1010,'Fines',NULL);                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (138,'Wiltshire','Accounting Division','0138',NULL,1037,'Fines',NULL);                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (139,'North Cheshire','Accounting Division','0139',NULL,1006,'Fines',NULL);                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (14,'Gloucestershire','Accounting Division','0051',NULL,1036,'Fines',NULL);                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (21,'Leicester','Accounting Division','0082',NULL,1021,'Fines',NULL);                                                                                                                                                                                                                                                                                                               

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (22,'Lincolnshire','Accounting Division','0084',NULL,1020,'Fines',NULL);                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (24,'Suffolk','Accounting Division','0121',NULL,1025,'Fines',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (26,'Hertfordshire','Accounting Division','0069',NULL,1027,'Fines',NULL);                                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (28,'North Yorkshire','Accounting Division','0095',NULL,1009,'Fines',NULL);                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (29,'Northants','Accounting Division','0096',NULL,1022,'Fines',NULL);                                                                                                                                                                                                                                                                                                               

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (30,'Norwich','Accounting Division','0093',NULL,1024,'Fines',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (31,'Oxfordshire','Accounting Division','0127',NULL,1029,'Fines',NULL);                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (36,'LCIS (South + Mid Glamorgan)','Accounting Division','0113',NULL,1041,'Fines',TRUE);                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (38,'Staffordshire','Accounting Division','0118',NULL,1015,'Fines',NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (45,'North West Confiscation Unit','Accounting Division','0055',NULL,2005,'Confiscation',NULL);                                                                                                                                                                                                                                                                                     

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (47,'Bristol','Accounting Division','0003',NULL,1035,'Fines',NULL);                                                                                                                                                                                                                                                                                                                 

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (5,'Cambridgeshire','Accounting Division','0009',NULL,1023,'Fines',NULL);                                                                                                                                                                                                                                                                                                           

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (52,'Bedfordshire','Accounting Division','0008',NULL,1026,'Fines',NULL);                                                                                                                                                                                                                                                                                                            

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (57,'Plymouth District','Accounting Division','0017',NULL,1034,'Fines',NULL);                                                                                                                                                                                                                                                                                                       

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (60,'Dyfed Powys','Accounting Division','0022',NULL,1042,'Fines',TRUE);                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (61,'Essex','Accounting Division','0023',NULL,1028,'Fines',NULL);                                                                                                                                                                                                                                                                                                                   

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (65,'Camden and Islington','Accounting Division','0034',NULL,1001,'Fines',NULL);                                                                                                                                                                                                                                                                                                    

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (66,'CAO Confiscation Orders','Accounting Division','0035',NULL,2001,'Confiscation',NULL);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (73,'West London','Accounting Division','0042',NULL,1001,'Fines',NULL);                                                                                                                                                                                                                                                                                                             

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (77,'Camberwell Green','Accounting Division','0046',NULL,1001,'Fines',NULL);                                                                                                                                                                                                                                                                                                        

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (78,'London NE','Accounting Division','0047',NULL,1001,'Fines',NULL);                                                                                                                                                                                                                                                                                                               

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (8,'Cleveland','Accounting Division','0011',NULL,1013,'Fines',NULL);                                                                                                                                                                                                                                                                                                                

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (80,'Historical Debt','Accounting Division','0049',NULL,1001,'Fines',NULL);                                                                                                                                                                                                                                                                                                         

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (82,'Bolton','Accounting Division','0056',NULL,1005,'Fines',NULL);                                                                                                                                                                                                                                                                                                                  

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (89,'Gwent','Accounting Division','0063',NULL,1040,'Fines',TRUE);                                                                                                                                                                                                                                                                                                                   

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (9,'Cumbria','Accounting Division','0012',NULL,1002,'Fines',NULL);                                                                                                                                                                                                                                                                                                                  

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (92,'East Hampshire','Accounting Division','0066',NULL,1030,'Fines',NULL);                                                                                                                                                                                                                                                                                                          

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (96,'South Bank','Accounting Division','0073',NULL,1012,'Fines',NULL);                                                                                                                                                                                                                                                                                                              

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (97,'South East Confiscation Unit','Accounting Division','0074',NULL,2032,'Confiscation',NULL);                                                                                                                                                                                                                                                                                     

INSERT INTO business_units (business_unit_id,business_unit_name,business_unit_type,business_unit_code,account_number_prefix,parent_business_unit_id,opal_domain,welsh_language)                                                                                                                                                                                                                    
        VALUES (99,'West Kent','Accounting Division','0076',NULL,1032,'Fines',NULL);                                                                                                                                                                                                                                                                                                                      
