/**
* CGI OPAL Program
*
* MODULE      : exported_bu_inserts.sql
*
* DESCRIPTION : The insert statements generated using pgAdmin Postgres from Reference Data CSV files to be used to populate the business_units table in the Fines model
*
* VERSION HISTORY:
*
* Date          Author      Version     Nature of Change
* ----------    -------     --------    --------------------------------------------------------------------------------------------------------------------------------------------------------------
* 13/05/2024    A Dennis    1.0         PO-306 The insert statements generated using pgAdmin Postgres from Reference Data CSV files to be used to populate the business_units table in the Fines model
*
**/
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (1, 'Avon and Somerset', '52', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (2, 'Bedfordshire', '40', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (3, 'Cambridgeshire', '35', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (4, 'Cheshire', '7', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (5, 'Cleveland', '17', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (6, 'Cumbria', '3', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (7, 'Derbyshire', '30', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (8, 'Devon and Cornwall', '50', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (9, 'Dorset', '55', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (10, 'Durham', '11', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (11, 'Dyfed Powys', '63', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (12, 'Essex', '42', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (13, 'Gloucestershire', '53', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (14, 'Greater Manchester', '6', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (15, 'Gwent', '61', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (16, 'Hampshire and Isle of Wight', '44', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (17, 'Hertfordshire', '41', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (18, 'Humberside', '16', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (19, 'Kent', '46', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (20, 'Lancashire', '4', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (21, 'Leicestershire', '33', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (22, 'Lincolnshire', '32', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (23, 'Greater London', '1', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (24, 'Merseyside', '5', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (25, 'Norfolk', '36', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (26, 'North Wales', '60', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (27, 'North Yorkshire', '12', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (28, 'Northamptonshire', '34', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (29, 'Northumbria', '10', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (30, 'Nottinghamshire', '31', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (31, 'South Wales', '62', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (32, 'South Yorkshire', '14', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (33, 'Staffordshire', '21', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (34, 'Suffolk', '37', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (35, 'Surrey', '45', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (36, 'Sussex', '47', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (37, 'Thames Valley', '43', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (38, 'Warwickshire', '23', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (39, 'West Mercia', '22', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (40, 'West Midlands', '20', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (41, 'West Yorkshire', '13', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (42, 'Wiltshire', '54', 'Area', NULL, NULL, NULL);
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (43, 'Avon and Somerset', '47', 'Accounting Division', NULL, 1, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (44, 'Bedfordshire', '52', 'Accounting Division', NULL, 2, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (45, 'Cambridgeshire', '5', 'Accounting Division', NULL, 3, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (46, 'Cheshire', '139', 'Accounting Division', NULL, 4, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (47, 'Cleveland', '8', 'Accounting Division', NULL, 5, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (48, 'Cumbria', '9', 'Accounting Division', NULL, 6, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (49, 'Derbyshire', '10', 'Accounting Division', NULL, 7, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (50, 'Devon and Cornwall', '57', 'Accounting Division', NULL, 8, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (51, 'Dorset', '11', 'Accounting Division', NULL, 9, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (52, 'Durham', '12', 'Accounting Division', NULL, 10, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (53, 'Dyfed Powys', '60', 'Accounting Division', NULL, 11, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (54, 'East Midlands Confiscation', '116', 'Accounting Division', NULL, 21, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (55, 'Essex', '61', 'Accounting Division', NULL, 12, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (56, 'Gloucestershire', '14', 'Accounting Division', NULL, 13, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (57, 'Greater Manchester', '82', 'Accounting Division', NULL, 14, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (58, 'Gwent', '89', 'Accounting Division', NULL, 15, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (59, 'Hampshire and Isle of Wight', '92', 'Accounting Division', NULL, 16, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (60, 'Hertfordshire', '26', 'Accounting Division', NULL, 17, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (61, 'Historical Debt', '80', 'Accounting Division', NULL, 23, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (62, 'Humber', '96', 'Accounting Division', NULL, 18, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (63, 'Kent', '99', 'Accounting Division', NULL, 19, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (64, 'Lancashire', '103', 'Accounting Division', NULL, 20, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (65, 'Leicestershire', '21', 'Accounting Division', NULL, 21, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (66, 'Lincolnshire', '22', 'Accounting Division', NULL, 22, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (67, 'London Central & South East', '77', 'Accounting Division', NULL, 23, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (68, 'London Confiscation Orders', '66', 'Accounting Division', NULL, 23, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (69, 'London North East', '78', 'Accounting Division', NULL, 23, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (70, 'London North West', '65', 'Accounting Division', NULL, 23, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (71, 'London South West', '73', 'Accounting Division', NULL, 23, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (72, 'MBEC England', '44', 'Accounting Division', NULL, 28, 'RM');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (73, 'MBEC London', '67', 'Accounting Division', NULL, 23, 'RM');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (74, 'MBEC Wales', '111', 'Accounting Division', NULL, 1, 'RM');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (75, 'Merseyside', '105', 'Accounting Division', NULL, 24, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (76, 'Norfolk', '30', 'Accounting Division', NULL, 25, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (77, 'North East Confiscation unit', '109', 'Accounting Division', NULL, 41, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (78, 'North Wales', '106', 'Accounting Division', NULL, 26, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (79, 'North West Confiscation Unit', '45', 'Accounting Division', NULL, 14, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (80, 'North Yorkshire', '28', 'Accounting Division', NULL, 27, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (81, 'Northants', '29', 'Accounting Division', NULL, 28, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (82, 'Northumbria', '112', 'Accounting Division', NULL, 29, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (83, 'Nottinghamshire', '119', 'Accounting Division', NULL, 30, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (84, 'South East Confiscation Unit', '97', 'Accounting Division', NULL, 19, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (85, 'South Wales', '36', 'Accounting Division', NULL, 31, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (86, 'South West Region Confiscation', '110', 'Accounting Division', NULL, 1, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (87, 'South Yorkshire', '124', 'Accounting Division', NULL, 32, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (88, 'Staffordshire', '38', 'Accounting Division', NULL, 33, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (89, 'Suffolk', '24', 'Accounting Division', NULL, 34, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (90, 'Surrey', '125', 'Accounting Division', NULL, 35, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (91, 'Sussex', '126', 'Accounting Division', NULL, 36, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (92, 'Thames Valley', '31', 'Accounting Division', NULL, 37, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (93, 'Wales Confiscation', '107', 'Accounting Division', NULL, 31, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (94, 'Warwickshire', '128', 'Accounting Division', NULL, 38, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (95, 'West Mercia', '129', 'Accounting Division', NULL, 39, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (96, 'West Midlands', '130', 'Accounting Division', NULL, 40, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (97, 'West Midlands Confiscation', '113', 'Accounting Division', NULL, 40, 'Confiscation');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (98, 'West Yorkshire', '135', 'Accounting Division', NULL, 41, 'Fines');
INSERT INTO business_units (business_unit_id, business_unit_name, business_unit_code, business_unit_type, account_number_prefix, parent_business_unit_id, opal_domain) VALUES (99, 'Wiltshire', '138', 'Accounting Division', NULL, 42, 'Fines');
