spring:
  # Flyway
  flyway:
    locations: classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/dev
    baseline-on-migrate: true
    ignoreMigrationPatterns: "*:missing"
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: false

  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration
      - org.springframework.boot.security.autoconfigure.actuate.web.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.security.oauth2.client.autoconfigure.OAuth2ClientAutoConfiguration
      -
launchdarkly:
  enabled: true
  sdk-key: integration-test-key
  file:
    - src/integrationTest/resources/launchdarkly-flags.json
  default-flag-values:
    release-1a: true
    release-1b: true
    release-1c-enforcement-operational-reporting: true
    release-1d-auto-enforcement-config: true

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: WARN

      springframework:
        jdbc:
          datasource:
            init: DEBUG
# Hibernate
jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true

testcontainers:
  reuse:
    enable: true
legacy-gateway:
  url: http://localhost:4553/opal
opal:
  report:
    consumer:
      enabled: false
  redis:
      enabled: true
user:
  service:
    url: http://localhost:4553/opal
