launchdarkly:
  enabled: false
  default-flag-values:
    is-legacy-mode: false
opal:
  redis:
    enabled: true
    ttl-duration: 8H
    hmrc-auth-token-ttl-duration: PT3H30M
hmrc:
  auth:
    client-id: test-hmrc-client-id
    client-secret: test-hmrc-client-secret
    scope: test-scope1+test-scope2
    url: https://localhost:4553/oauth/token
