/**
* OPAL Program
*
* MODULE      : insert_local_justice_areas.sql
*
* DESCRIPTION : Insert data into LOCAL_JUSTICE_AREAS table
*
* VERSION HISTORY:
*
* Date          Author       Version     Nature of Change
* ----------    --------     --------    ---------------------------------------------------------------------------------------------------------
* 25/04/2025    C Cho        1.0         PO-1130 Insert reference data for local justice areas
*
**/

DELETE FROM local_justice_areas;
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date, lja_type) VALUES 
('101', 'Aberdare County Court', 'Crown Building', 'Green Street', 'Aberdare, Mid Glam.', 'CF44 7DW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('102', 'Aberystwyth County Court', 'Edleston House', 'Queens Road', 'Aberystwyth, Ceredigion', 'SY23 2HP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('103', 'Accrington County Court', 'Bradshawgate House', '1 Oak Street', 'Accrington, Lancs.', 'BB5 1EQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('106', 'Altrimcham County Court', 'PO Box 240', 'Trafford Courthouse', 'Ashton Lane, Sale', 'M33 7WX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('111', 'Ashford County Court', 'Ground Floor', 'The Court House', 'Tufton Street, Ashford', 'TN23 1QQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('112', 'Tameside County Court', 'PO Box 166', 'Henry Square', 'Ashton-under-Lyne, Lancs.', 'OL6 7TP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('113', 'Aylesbury County Court', 'Second Floor', 'Heron House', '49 Buckingham Street', 'HP20 2NQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('114', 'Banbury County Court', '35 Parsons Street', 'Banbury', 'Oxon.', 'OX16 8BW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('117', 'Barnet County Court', 'St. Mary''s Court', 'Regents Park Road', 'Finchley Central, London', 'N3 1BQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('118', 'Barnsley County Court', '12 Regent Street', 'Barnsley', 'S. Yorks.', 'S70 2EW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('119', 'Barnstaple County Court', '7th Floor', 'Civic Centre', 'North Walk, Barnstaple', 'EX31 1DY', NULL, NULL, NULL, NULL, 'CTYCRT'),
('120', 'Barrow-in-Furness County Court', 'Government Buildings', 'Michaelson Road', 'Barrow-in-Furness, Cumbria', 'LA14 2EZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('122', 'Basingstoke County Court', '3rd Floor', 'Grosvenor House', 'Basing View, Basingstoke', 'RG21 4HG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('123', 'Bath County Court', '3rd & 4th Floor', 'Cambridge House', 'Henry Street, Bath', 'BA1 1DJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('124', 'Bedford County Court', 'May House', '29 Goldington Road', 'Bedford', 'MK40 3NN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('126', 'Birkenhead County Court', '76 Hamilton Street', 'Birkenhead', 'Merseyside', 'CH41 5EN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('130', 'Blackburn County Court', '64 Victoria Street', 'Blackburn', 'Lancs.', 'BB1 6DJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('131', 'Blackpool County Court', 'The Law Courts', 'Chapel Street', 'Blackpool, Lancs.', 'FY1 5RJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('132', 'Blackwood County Court', 'COUNTY COURT OFFICES', 'Blackwood Road', 'Blackwood', 'NP2 2XB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('136', 'Bodmin County Court', 'Cockswell House', 'Market Street', 'Bodmin, Cornwall', 'PL31 2HJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('137', 'Bolton County Court', 'The Law Courts', 'Blackhorse Street', 'Bolton, Lancs.', 'BL1 1SU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('138', 'Boston County Court', '55 Norfolk Street', 'Boston', 'Lincs.', 'PE21 6PE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('139', 'Bournemouth County Court', 'Courts of Justice', 'Deansleigh Road', 'Bournemouth', 'BH7 7DS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('140', 'Bow County Court', '96 Romford Road', 'Stratford', 'London', 'E15 4EG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('141', 'Bradford County Court', 'Bradford Combined Court Centre', 'Exchange Square', 'Drake Street, Bradford', 'BD1 1JA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('143', 'Brecknock County Court', 'Cambrian Way', 'Brecon', 'Powys', 'LD3 7HR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('144', 'Brentford County Court', 'Alexandra Road', 'High Street', 'Brentford, Middlesex', 'TW8 0JJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('146', 'Bridgend County Court', 'Crown Buildings', 'Angel Street', 'Bridgend, Mid Glam.', 'CF31 4AS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('150', 'Brighton County Court', 'Brighton County Court Family C', '1 Edward Street', 'Brighton, East Sussex', 'BN2 2JD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('151', 'Bristol County Court', 'Greyfriars', 'Lewins Mead', 'Bristol', 'BS1 2NR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('152', 'Bromley County Court', 'Court House', 'College Road', 'Bromley, Kent', 'BR1 3PX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('153', 'Basildon County Court', 'Basildon Combined Court', 'The Gore', 'Basildon, Essex', 'SS14 2EU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('154', 'Burnley County Court', 'The Law Courts', 'Hammerton Street', 'Burnley, Lancs.', 'BB11 1XD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('155', 'Burton-upon-Trent County Court', '165 Station Street', 'Burton-upon-Trent', 'Staffs.', 'DE14 1BP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('156', 'Bury County Court', 'Tenterden Street', 'Bury', 'Lancs.', 'BL9 0HJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('157', 'Bury St. Edmunds County Court', 'Triton House (Entrance B)', 'St. Andrews Street North', 'Bury St. Edmunds, Suffolk', 'IP33 1TR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('158', 'Buxton County Court', '1-3 Hardwick Street', 'Buxton', 'Derbys.', 'SK17 6DH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('159', 'Caernarfon County Court', 'Court House', 'Llanberis Road', 'Caernarfon, Gwynedd', 'LL55 2DF', NULL, NULL, NULL, NULL, 'CTYCRT'),
('162', 'Cambridge County Court', 'Bridge House', 'Bridge Street', 'Cambridge', 'CB2 1UA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('163', 'Canterbury County Court', 'Canterbury Combined Court Cent', 'Law Courts', 'Chaucer Road, Canterbury', 'CT1 1ZA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('164', 'Cardiff County Court', 'Cardiff Civil Justice Centre', '2 Park Street', 'Cardiff', 'CF10 1ET', NULL, NULL, NULL, NULL, 'CTYCRT'),
('165', 'Carlisle County Court', 'Carlisle Combined Court Centre', 'Courts of Justice', 'Earl Street, Carlisle', 'CA1 1DJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('166', 'Carmarthen County Court', 'The Old Vicarage', 'Picton Terrace', 'Carmarthen, Dyfed', 'SA31 1BJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('167', 'Chelmsford County Court', 'London House', 'New London Road', 'Chelmsford, Essex', 'CM2 0QR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('168', 'Cheltenham County Court', 'The Court House', 'County Court Road', 'Cheltenham, Glos.', 'GL50 1HB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('170', 'Chester County Court', 'Trident House', 'Little St. John Street', 'Chester', 'CH1 1SN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('171', 'Chesterfield County Court', 'St. Mary''s Gate', 'Chesterfield', 'Derbys.', 'S41 7TD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('172', 'Chichester County Court', 'Chichester Combined Court Cent', 'Southgate', 'Chichester, W. Sussex', 'PO19 1SX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('173', 'Colchester County Court', 'Falkland House', '25 Southway', 'Colchester, Essex', 'CO3 3EG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('174', 'Chorley County Court', '59 St. Thomas''s Road', 'Chorley', 'Lancs.', 'PR7 1JE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('175', 'Clerkenwell County Court', '33 Duncan Terrace', 'Islington', 'London', 'N1 8AN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('177', 'Consett County Court', 'Victoria Road', 'Consett', 'Durham', 'DH8 5AU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('178', 'Conwy and Colwyn County Court', '36 Princes Drive', 'Colwyn Bay', NULL, 'LL29 8LA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('180', 'Coventry County Court', 'Coventry Combined Court Centre', '140 Much Park Street', 'Coventry', 'CV1 2SN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('181', 'Crewe County Court', 'The Law Courts', 'Civic Centre', 'Crewe, Cheshire', 'CW1 2DP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('182', 'Croydon County Court', 'The Law Courts', 'Altyre Road', 'Croydon', 'CR9 5AB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('183', 'Darlington County Court', '4 Coniscliffe Road', 'Darlington', 'Co. Durham', 'DL3 7RL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('184', 'Dartford County Court', 'Court House', 'Home Gardens', 'Dartford, Kent', 'DA1 1DX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('185', 'Derby County Court', 'Derby Combined Court Centre', 'Morledge', 'Derby', 'DE1 2XE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('186', 'Dewsbury County Court', 'County Court House', 'Eightlands Road', 'Dewsbury, W. Yorks.', 'WF13 2PE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('187', 'Doncaster County Court', '74 Waterdale', 'Doncaster', 'S. Yorks.', 'DN1 3BT', NULL, NULL, NULL, NULL, 'CTYCRT'),
('189', 'Dudley County Court', 'Harbour Buildings', 'Waterfront West', 'Brierley Hill, West Midlands', 'DY5 1LN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('190', 'Durham County Court', 'Hallgarth Street', 'Durham', NULL, 'DH1 3RG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('191', 'Eastbourne County Court', '4 The Avenue', 'Eastbourne', 'E. Sussex', 'BN21 3SZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('194', 'Edmonton County Court', 'Court House', '59 Fore Street', 'Upper Edmonton, London', 'N18 2TN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('196', 'Epsom County Court', 'The Parade', 'Epsom', 'Surrey', 'KT18 5DN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('197', 'Evesham County Court', '1sr Floor', '87 High Street', 'Evesham, Worcs.', 'WR11 4EE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('198', 'Exeter County Court', 'Exeter Combined Court Centreq', 'The Castle', 'Exeter, Devon', 'EX4 3PS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('202', 'Gateshead County Court', '5th Floor', 'Chad House', 'Tyngate Precinct, Gateshead', 'NE8 3HZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('203', 'Gloucester County Court', 'County Court Offices', 'Kimbrose Way', 'Gloucester', 'GL1 2DE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('205', 'Grantham County Court', '10 Guildhall Street', 'Grantham', 'Lincs.', 'NG31 6NJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('206', 'Gravesend County Court', '26 King Street', 'Gravesend', 'Kent', 'DA12 2DU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('208', 'Great Grimsby County Court', 'Great Grimsby Combined Court C', 'Town Hall Square', 'Grimsby, N.E. Lincs.', 'DN31 1HX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('211', 'Guildford County Court', 'The Law Courts', 'Mary Road', 'Guildford, Surrey', 'GU1 4PS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('212', 'Halifax County Court', 'Prescott Street', 'Halifax', 'W. Yorks.', 'HX1 2JJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('213', 'Harlow County Court', 'Gate House', 'The High', 'Harlow, Essex', 'CM20 1UW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('214', 'Harrogate County Court', '2 Victoria Avenue', 'Harrogate', 'N. Yorks.', 'HG1 2EL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('215', 'Hartlepool County Court', 'Law Courts', 'Victoria Road', 'Hartlepool', 'TS24 8BS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('216', 'Hastings County Court', 'Law Courts', 'Bohemia Road', 'Hastings, E. Sussex', 'TN34 1QX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('217', 'Haverfordwest County Court', 'Penffynnon', 'Hawthorn Rise', 'Haverfordwest, Pembs.', 'SA61 2AZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('218', 'Haywards Heath County Court', 'Milton House', 'Milton Road', 'Haywards Heath, West Sussex', 'RH16 1YZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('220', 'Hereford County Court', 'First Floor', 'Barclays Bank Chambers', '1/3 Broad Street, Hereford', 'HR4 9BA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('221', 'Hertford County Court', '4th Floor', 'Sovereign House', 'Hale Road, Hertford', 'SG13 8DY', NULL, NULL, NULL, NULL, 'CTYCRT'),
('223', 'High Wycombe County Court', 'The Law Courts', 'Ground Floor', 'Easton Street, High Wycombe', 'HP11 1LR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('225', 'Hitchin County Court', 'Park House', '1-12 Old Park Road', 'Hitchin, Herts.', 'SG5 1LX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('227', 'Horsham County Court', 'The Law Courts', 'Hurst Road', 'Horsham, Sussex', 'RH12 2EU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('228', 'Huddersfield County Court', 'Queensgate House', 'Queensgate', 'Huddersfield', 'HD1 2RR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('229', 'Huntingdon County Court', 'Ground Floor', 'Godwin House', 'George Street, Huntingdon', 'PE29 3BD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('231', 'Ilford County Court', 'Buckingham Road', 'Ilford', 'Essex', 'IG1 1BR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('233', 'Ipswich County Court', '8 Arcade Street', 'Ipswich', 'Suffolk', 'IP1 1EJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('234', 'Keighley County Court', 'Yorkshire Bank Chambers', 'North Street', 'Keighley, W. Yorks.', 'BD21 3SH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('235', 'Kendal County Court', 'The Court House', 'County Court Road', 'Burneside Road, Kendal', 'LA9 4NF', NULL, NULL, NULL, NULL, 'CTYCRT'),
('236', 'Kettering County Court', 'Dryland Street', 'Kettering', 'Northants.', 'NN16 0BE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('237', 'Kidderminster County Court', '10 Comberton Place', 'Kidderminster', NULL, 'DY10 1QR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('238', 'King''s Lynn County Court', 'Chequer House', '12 King Street', 'King''s Lynn, Norfolk', 'PE30 1ES', NULL, NULL, NULL, NULL, 'CTYCRT'),
('239', 'Kingston-upon-Hull County Ct.', 'Kingston-upon-Hull Combined Ct', 'Lowgate', 'Hull', 'HU1 2EZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('240', 'Kingston-upon-Thames County Ct', 'St. James''s Road', 'Kingston-upon-Thames', 'Surrey', 'KT1 2AD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('241', 'Lambeth County Court', 'Court House', 'Cleaver Street', 'Kennington Road, London', 'SE11 4DZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('242', 'Lancaster County Court', '2nd Floor', 'Mitre House', 'Church Strret, Lancaster', 'LA1 1UZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('243', 'Leeds County Court', 'Leeds Combined Court Centre', '1 Oxford Row', 'Leeds', 'LS1 3BG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('244', 'Leicester County Court', 'PO Box 3', '90 Wellington Street', 'Leicester', 'LE1 6ZZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('245', 'Leigh County Court', '22 Walmesley Road', 'Leigh', 'Lancs.', 'WN7 1YF', NULL, NULL, NULL, NULL, 'CTYCRT'),
('247', 'Lewes County Court', 'Lewes Combined Court Centre', 'The Law Courts', 'High Street, Lewes', 'BN7 1YB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('249', 'Lincoln County Court', 'Lincoln Combined Court Centre', '360 High Street', 'Lincoln', 'LN5 7PS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('251', 'Liverpool County Court', 'The Queen Elizabeth II Law Cou', 'Derby Square', 'Liverpool', 'L2 1XA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('253', 'Llanelli County Court', '2nd Floor', 'Court Buildings', 'Town Hall Square, Llanelli', 'SA15 3AL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('254', 'Llangefni County Court', 'County Court Buildings', 'Glanhwfa Road', 'Llangefni, Anglesey', 'LL77 7EN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('256', 'Lowestoft County Court', 'Lyndhurst', '28 Gordon Road', 'Lowestoft, Suffolk', 'NR32 1NL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('257', 'Ludlow County Court', '9-10 King Street', 'Ludlow', 'Shropshire', 'SY8 1QW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('258', 'Luton County Court', '5th Floor', 'Cresta House', 'Alma Street, Luton', 'LU1 2PU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('260', 'Macclesfield County Court', '2nd Floor', 'Silk House', 'Park Green, Macclesfield', 'SK11 7NA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('261', 'Midstone County Court', 'Maidstone Combined Court Centr', 'Barker Road', 'Maidstone, Kent', 'ME16 8EQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('262', 'Manchester County Court', 'Courts of Justice', 'Crown Square', 'Manchester', 'M60 9DJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('263', 'Mansfield County Court', 'Beech House', '58 Commercial Gate', 'Mansfield, Notts.', 'NG18 1EU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('267', 'Medway County Court', 'Anchorage House', '47-67 High Street', 'Chatham, Kent', 'ME4 4DW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('268', 'Melton Mowbray County Court', 'Crown House', '50/52 Scalford Road', 'Melton Mowbray, Leics.', 'LE13 1JY', NULL, NULL, NULL, NULL, 'CTYCRT'),
('269', 'Merthyr Tydfil County Court', 'Merthyr Tydfil Combined Court', 'The Law Courts', 'Glebeland Place', 'CF47 8BH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('270', 'Middlesbrough County Court', 'Teesside Combined Court Centre', 'Russell Street', 'Middlesbrough, Cleveland', 'TS1 2AE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('271', 'Mold County Court', 'Law Courts', 'County Civic Centre', 'Mold, Flintshire', 'CH7 1AE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('273', 'Morpeth & Berwick County Court', 'Fountain House', 'Newmarket', 'Morpeth, Northumberland', 'NE61 1LA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('274', 'Neath & Port Talbot County Ct.', 'Forster Road', 'Neath', 'W. Glam', 'SA11 3BN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('275', 'Nelson County Court', 'Phoenix Chambers', '9/13 Holme Street', 'Nelson, Lancs.', 'BB9 9SU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('276', 'Newark County Court', 'Crown Building', '41 Lombard Street', 'Newark, Notts.', 'NG24 1XB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('277', 'Newbury County Court', 'Kings Road West', 'Newbury', 'Berks.', 'RG14 5BY', NULL, NULL, NULL, NULL, 'CTYCRT'),
('278', 'Newcastle upon Tyne County Ct.', 'Newcastle upon Tyne Combined', 'The Law Courts', 'Quayside, Newcastle upon Tyne', 'NE1 3LA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('279', 'Newport (I.O.W.) County Court', 'Newport (I.O.W.) Crown and Cou', '1 Quay Street', 'Newport, I.O.W.', 'PO30 5YT', NULL, NULL, NULL, NULL, 'CTYCRT'),
('280', 'Newport (Sth.Wales)County Ct.', '3rd Floor', 'Olympia House', 'Upper Dock Street, Newport', 'NP20 1PQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('282', 'Northampton County Court', 'Northampton Combined Court Cen', '85/87 Lady''s Lane', 'Northampton', 'NN1 3HQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('283', 'North Shields County Court', 'Northumbria House', 'Norfolk Street', 'North Shields, Tyne and Wear', 'NE30 1EX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('284', 'Northwich County Court', '25/27 High Street', 'Northwich', 'Cheshire', 'CW9 5DB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('285', 'Norwich County Court', 'Norwich Combined Court Centre', 'The Law Courts', 'Bishopgate, Norwich', 'NR3 1UR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('286', 'Nottingham County Court', 'The Law Courts', '60 Canal Street', 'Nottingham', 'NG1 7EJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('287', 'Nuneaton County Court', 'Heron House', 'Newdedate Street', 'Nuneaton, Warwickshire', 'CV11 4EL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('288', 'Oldham County Court', 'County Court House', 'New Radcliffe Street', 'Oldham', 'OL1 1NL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('289', 'Oswestry County Court', '2nd Floor', 'The Guildhall', 'Bailey Head, Oswestry', 'SY11 2EW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('291', 'Oxford County Court', 'Oxford Combined Court Centre', 'St. Aldates', 'Oxford', 'OX1 1TL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('292', 'Penrith County Court', 'The Court House', 'Lowther Terrace', 'Penrith, Cumbria', 'CA11 7QL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('293', 'Penzance County Court', 'Trevear', 'Alverton', 'Penzance, Cornwall', 'TR18 4GH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('294', 'Peterborough County Court', 'Peterborough Combined Court Ce', 'Crown Buildings', 'Rivergate, Peterborough', 'PE1 1EJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('296', 'Plymouth County Court', 'Plymouth Combined Court Centre', 'The Law Courts', 'Armada Way, Plymouth', 'PL1 2ER', NULL, NULL, NULL, NULL, 'CTYCRT'),
('297', 'Pontefract County Court', 'Horsefair House', 'Horsefair', 'Pontefract, W. Yorks.', 'WF8 1RJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('298', 'Pontypool County Court', 'Court Offices', 'Park Road', 'Riverside, Pontypool', 'NP4 6NZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('299', 'Pontypridd County Court', 'The Courthouse', 'Courthouse Street', 'Pontypridd, Mid Glamorgan', 'CF37 1JR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('300', 'Poole County Court', 'Law Courts', 'Civic Centre', 'Park Road, Poole', 'BN15 2NS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('302', 'Portsmouth County Court', 'Portsmouth Combined Court Cent', 'The Courts of Justice', 'Winston Churchill Avenue', 'PO1 2EB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('303', 'Preston County Court', 'Preston Combined Court Centre', 'The Law Courts', 'Openshaw Place, Ringway', 'PR1 2LL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('304', 'Rawtenstall County Court', '1 Grange Street', 'Rawtenstall', 'Lancs.', 'BB4 7RT', NULL, NULL, NULL, NULL, 'CTYCRT'),
('305', 'Reading County Court', '160-163 Friar Street', 'Reading', NULL, 'RG1 1HE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('306', 'Redditch County Court', 'Court Office', '13 Church Road', 'Redditch, Worcs.', 'B97 4AB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('307', 'Reigate County Court', 'Law Courts', 'Hatchlands Road', 'Redhill, Surrey', 'RH1 6BL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('308', 'Rhyl County Court', 'The Courthouse', 'Clwyd Street', 'Rhyl, Denbighshire', 'LL18 3LA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('310', 'Rotherham County Court', 'Portland House', 'Mansfield Road', 'Rotherham, S. Yorks.', 'S60 2BX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('311', 'Rugby County Court', '5 Newbold Road', 'Rugby', NULL, 'CV21 2RN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('312', 'Runcorn County Court', 'The Law Courts', 'Legh Street', 'Warrington, Cheshire', 'WA1 1UR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('313', 'St. Albans County Court', 'Victoria House', '117 Victoria Street', 'St. Albans', 'AL1 3TJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('315', 'St. Helens County Court', '1st Floor', 'Rexmore House', 'Cotham Street, St. Helens', 'WA10 1SE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('316', 'Salford County Court', 'Prince William House', 'Peel Cross Road', 'Salford', 'M5 4RR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('317', 'Salisbury County Court', 'Courts of Justice', 'Alexandra House', 'St. John Street, Salisbury', 'SP1 2PN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('318', 'Scarborough County Court', 'Pavilion House', 'Valley Bridge Road', 'Scarborough, N. Yorks.', 'YO11 2JS', NULL, NULL, NULL, NULL, 'CTYCRT'),
('319', 'Scunthorpe County Court', 'Crown Building', 'Comforts Avenue', 'Scunthorpe, N. Lincs.', 'DN15 6PR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('320', 'Sheffield County Court', 'Sheffield Combined Court Centr', 'The Law Courts', '50 West Bar, Sheffield', 'S3 8PH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('321', 'Shoreditch County Court', '19 Leonard Street', 'London', NULL, 'EC2A 4AL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('322', 'Shrewsbury County Court', '4th Floor', 'Cambrian Business Centre', 'Chester Street, Shrewsbury', 'SY1 1NA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('324', 'Skegness County Court', 'Town Hall Annexe', 'North Parade', 'Skegness, Lincolnshire', 'PE25 1DA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('325', 'Skipton County Court', 'The Court House', 'Otley Street', 'Skipton, N. Yorks.', 'BD23 1RH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('327', 'Slough County Court', 'The Law Courts', 'Windsor Road', 'Slough', 'SL1 2HE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('328', 'Southampton County Court', 'Southampton Combined Court Cen', 'The Courts of Justice', 'London Road, Southampton', 'SO15 2XQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('329', 'Southend County Court', 'Tylers House', 'Tylers Avenue', 'Southen-on-Sea, Essex', 'SS1 2AW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('330', 'Southport County Court', 'The Duke''s House', '34 Hoghton Street', 'Southport, Merseyside', 'PR9 0PU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('331', 'South Shields County Court', '25/26 Market Place', 'South Shields', 'Tyne and Wear', 'NE33 1AG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('333', 'Stafford County Court', 'Stafford Combined Court Centre', 'Victoria Square', 'Stafford', 'ST16 2QQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('334', 'Staines County Court', 'The Law Courts', 'Knowle Green', 'Staines, Middlesex', 'TW18 1XH', NULL, NULL, NULL, NULL, 'CTYCRT'),
('336', 'Stockport County Court', 'Heron House', 'Wellington Street', 'Stockport, Cheshire', 'SK1 3DJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('338', 'Stoke-on-Trent County Court', 'Stoke-on-Trent Combined Court', 'Bethesda Street', 'Hanley, Stoke-on-Trent', 'ST1 3BP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('339', 'Stourbridge County Court', '7 Hagley Road', 'Stourbridge', 'W. Mids.', 'DY8 1QL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('340', 'Stratford-upon-Avon County Ct.', '5 Elm Court', 'Arden Street', 'Stratford-upon-Avon', 'CV37 6PA', NULL, NULL, NULL, NULL, 'CTYCRT'),
('343', 'Sunderland County Court', 'The Court House', '44 John Street', 'Sunderland', 'SR1 1RB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('344', 'Swansea County Court', 'Caravella House', 'Quay West', 'Quay Parade, Swansea', 'SA1 1SP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('345', 'Swindon County Court', 'Swindon Combined Court Centre', 'The Law Courts', 'Islington Street, Swindon', 'SN1 2HG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('346', 'Tamworth County Court', 'The Precinct', 'Lower Gungate', 'Tamworth, Staffs', 'B79 7AJ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('347', 'Taunton County Court', 'Shire Hall', 'Taunton', 'Somerset', 'TA1 4EU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('348', 'Thanet County Court', 'Capital House', 'Northdown Road', 'Cliftonville, Margate', 'CT9 1EQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('353', 'Trowbridge County Court', 'Ground Floor', 'Clarks Mill', 'Stallard Street, Trowbridge', 'BA14 8DB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('354', 'Truro County Court', 'Truro Combined Court Centre', 'Courts of Justice', 'Edward Street, Truro', 'TR1 2PB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('355', 'Tunbridge Wells County Court', 'Merevale House', '42-46 London Road', 'Tunbridge Wells, Kent', 'TN1 1DP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('356', 'Uxbridge County Court', '501 Uxbridge Road', 'Hayes', 'Middlesex', 'UB4 8HL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('357', 'Wakefield County Court', 'Crown House', '127 Kirkgate', 'Wakefield, W. Yorks.', 'WF1 1JW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('358', 'Walsall County Court', 'Bridge House', 'Bridge Street', 'Walsall, W. Mids.', 'WS1 1JQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('359', 'Wandsworth County Court', '76/78 Upper Richmond Road', 'Putney', 'London', 'SW15 2SU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('360', 'Warrington County Court', 'The Law Courts', 'Legh Street', 'Warrington', 'WA1 1UR', NULL, NULL, NULL, NULL, 'CTYCRT'),
('361', 'Warwick County Court', 'Warwick Combined Court Centre', 'Northgate South Side', 'Watford', 'CV34 4RB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('362', 'Watford County Court', 'Cassionbury House', '11-19 Station Road', 'Watford, Herts.', 'WD1 1EZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('363', 'Wellingborough County Court', 'Lothersdale House', 'West Villa Road', 'Wellinbgborough, Northants.', 'NN8 4NF', NULL, NULL, NULL, NULL, 'CTYCRT'),
('364', 'Telford County Court', 'Telford Square', 'Malinsgate', 'Town Centre, Telford', 'TF3 4JP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('366', 'Welshpool & Newtown County Ct.', 'The Mansion House', '24 Severn Street', 'Welshpool, Powys', 'SY21 7UX', NULL, NULL, NULL, NULL, 'CTYCRT'),
('368', 'West London County Court', '43 North End Road', 'W. Kensington', 'London', 'W14 8SZ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('370', 'Weston-super-Mare County Court', 'Regent House', 'High Street', 'Weston-super-Mare', 'BS23 1JF', NULL, NULL, NULL, NULL, 'CTYCRT'),
('371', 'Weymouth County Court', 'Weymouth and Dorchester Combin', 'Westwey House', 'Westwey Road, Weymouth', 'DT4 8TE', NULL, NULL, NULL, NULL, 'CTYCRT'),
('372', 'Central London County Court', '13-14 Park Crescent', 'London', NULL, 'W1N 4HT', NULL, NULL, NULL, NULL, 'CTYCRT'),
('373', 'Whitehaven County Court', 'Old Town Hall', 'Duke Street', 'Whitehaven, Cumbria', 'CA28 7NU', NULL, NULL, NULL, NULL, 'CTYCRT'),
('374', 'Wigan County Court', 'Crawford Street', 'Wigan', 'Lancs.', 'WN1 1NG', NULL, NULL, NULL, NULL, 'CTYCRT'),
('375', 'Willesden County Court', '9 Acton Lane', 'Harlesden', 'London', 'NW10 8SB', NULL, NULL, NULL, NULL, 'CTYCRT'),
('376', 'Winchester County Court', 'Winchester Combined Court Cent', 'The Law Courts', 'Winchester, Hants..', 'SO23 9EL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('379', 'Woolwich County Court', 'The Court House', 'Powis Street', 'Ldondon', 'SE18 6JW', NULL, NULL, NULL, NULL, 'CTYCRT'),
('380', 'Worcester County Court', 'Worcester Combined Court Centr', 'Shire Hall', 'Foregate Street, Worcester', 'WR1 1EQ', NULL, NULL, NULL, NULL, 'CTYCRT'),
('382', 'Worksop County Court', '8 Slack Walk', 'Worksop', 'Notts.', 'S80 1LN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('383', 'Worthing County Court', 'The Law Courts', 'Christchurch Road', 'Worthing, West Sussex', 'BN11 1JD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('384', 'Wrexham County Court', '2nd Floor', 'Crown Buildings', '31 Chester Street, Wrexham', 'LL13 8XN', NULL, NULL, NULL, NULL, 'CTYCRT'),
('385', 'Yeovil County Court', '22 Hendford', 'Yeovil', 'Somerset', 'BA20 2QD', NULL, NULL, NULL, NULL, 'CTYCRT'),
('386', 'York County Court', 'Piccadilly House', '55 Piccadilly', 'York', 'YO1 9WL', NULL, NULL, NULL, NULL, 'CTYCRT'),
('387', 'Romford County Court', '2A Oaklands Avenue', 'Romford', 'Essex', 'RM1 4DP', NULL, NULL, NULL, NULL, 'CTYCRT'),
('388', 'Milton Keynes County Court', '351 Silbury Boulevard', 'Witan Gate East', 'Central Milton Keynes', 'MK9 2DT', NULL, NULL, NULL, NULL, 'CTYCRT'),
('401', 'Aylesbury Crown Court', 'Walton Street', 'Aylesbury', 'Buckinghamshire', 'HP21 7FT', NULL, NULL, NULL, NULL, 'CRWCRT'),
('402', 'Bradford Crown Court', 'Bradford Combined Court Centre', 'Bradford Law Courts', 'Exchange Square', 'BD1 1JA', NULL, 'Drake Street', 'Bradford', NULL, 'CRWCRT'),
('403', 'Kingston-upon-Hull Crown Court', 'Kingston-upon-Hull Combined Court', 'Lowgate', 'Humberside', 'HU1 2EZ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('404', 'Birmingham Crown Court', 'Queen Elizabeth II Law Courts', '1 Newton Street', 'Birmingham', 'B4 7NA', NULL, NULL, NULL, NULL, 'CRWCRT'),
('406', 'Bournemouth Crown Court', 'Courts of Justice', 'Deansleigh Road', 'Bournemouth', 'BH7 7DS', NULL, 'Dorset', NULL, NULL, 'CRWCRT'),
('407', 'Dorchester Crown Court', 'County Hall', 'Dorchester', 'Dorset', NULL, NULL, NULL, NULL, NULL, 'CRWCRT'),
('408', 'Bristol Crown Court', 'The Law Courts', 'Small Street', 'Bristol', 'BS1 1DA', NULL, NULL, NULL, NULL, 'CRWCRT'),
('409', 'Burnley Crown Court', 'Burnley Combined Court Centre', 'The Law Courts', 'Hammerton Street', 'BB11 1XD', NULL, 'Burnley', 'Lancashire', NULL, 'CRWCRT'),
('410', 'Cambridge Crown Court', '83 East Road', 'Cambridge', NULL, 'CB1 1BT', NULL, NULL, NULL, NULL, 'CRWCRT'),
('411', 'Cardiff Crown Court', 'The Law Courts', 'Cathays Park', 'Cardiff', 'CF10 3PG', NULL, NULL, NULL, NULL, 'CRWCRT'),
('412', 'Carlisle Crown Court', 'Carlisle Combined Court Centre', 'Courts of Justice', 'Earl Street', 'CA1 1DJ', NULL, 'Carlisle', 'Cumbria', NULL, 'CRWCRT'),
('413', 'Central Criminal Court', 'Old Bailey', 'London', NULL, 'EC4M 7EH', NULL, NULL, NULL, NULL, 'CRWCRT'),
('414', 'Chelmsford Crown Court', 'New Street', 'Chelmsford', 'Essex', 'CM1 1EL', NULL, NULL, NULL, NULL, 'CRWCRT'),
('415', 'Chester Crown Court', 'The Castle', 'Chester', 'Cheshire', 'CH1 2AN', NULL, NULL, NULL, NULL, 'CRWCRT'),
('416', 'Chichester Crown Court', 'Chichester Combined Court Centre', 'Southgate', 'Chichester', 'PO19 1SX', NULL, 'West Sussex', NULL, NULL, 'CRWCRT'),
('417', 'Coventry Crown Court', 'Coventry Combined Court Centre', '140 Much Park Street', 'Coventry', 'CV1 2SN', NULL, 'West Midlands', NULL, NULL, 'CRWCRT'),
('418', 'Croydon Crown Court', 'The Law Courts', 'Altyre Road', 'Croydon', 'CR9 5AB', NULL, 'Surrey', NULL, NULL, 'CRWCRT'),
('419', 'Derby Crown Court', 'Derby Combined Court Centre', 'Morledge', 'Derby', 'DE1 2XE', NULL, NULL, NULL, NULL, 'CRWCRT'),
('420', 'Doncaster Crown Court', 'College Road', 'Doncaster', 'South Yorkshire', 'DN1 3HS', NULL, NULL, NULL, NULL, 'CRWCRT'),
('421', 'Wolverhampton Crown Court', 'Wolverhampton Combined Court Centre', 'Pipers Row', 'Wolverhampton', 'WV1 3LQ', NULL, 'West Midlands', NULL, NULL, 'CRWCRT'),
('422', 'Durham Crown Court', 'The Law Courts', 'Old Elvet', 'Durham', 'DH1 3HW', NULL, NULL, NULL, NULL, 'CRWCRT'),
('423', 'Exeter Crown Court', 'Exeter Combined Court Centre', 'Southernhay Gardens', 'Exeter', 'EX1 1UH', NULL, NULL, NULL, NULL, 'CRWCRT'),
('424', 'Gloucester Crown Court', 'Longsmith Street', 'Gloucester', 'Gloucestershire', 'GL1 2TS', NULL, NULL, NULL, NULL, 'CRWCRT'),
('425', 'Great Grimsby Crown Court', 'Great Grimsby Combined Court Centre', 'Town Hall Square', 'Grimsby', 'DN31 1HX', NULL, 'Lincolnshire', NULL, NULL, 'CRWCRT'),
('426', 'Ipswich Crown Court', 'The Courthouse', '1 Russell Road', 'Ipswich', 'IP1 2AG', NULL, 'Suffolk', NULL, NULL, 'CRWCRT'),
('427', 'Kingston upon Thames Crown Court', '6-8 Penrhyn Road', 'Kingston-upon-Thames', 'Surrey', 'KT1 2BB', NULL, NULL, NULL, NULL, 'CRWCRT'),
('428', 'Blackfriars Crown Court', '1-15 Pocock Street', 'London', NULL, 'SE1 0BT', NULL, NULL, NULL, NULL, 'CRWCRT'),
('429', 'Leeds Crown Court', 'Leeds Combined Court Centre', 'The Court House', '1 Oxford Row', 'LS1 3BG', NULL, 'Leeds', NULL, NULL, 'CRWCRT'),
('430', 'Leicester Crown Court', '90 Wellington Street', 'Leicester', 'Leicestershire', 'LE1 6HG', NULL, NULL, NULL, NULL, 'CRWCRT'),
('431', 'Lewes Crown Court', 'Lewes Combined Court Centre', 'The Law Courts', 'High Street', 'BN7 1YB', NULL, 'Lewes', 'East Sussex', NULL, 'CRWCRT'),
('432', 'Lincoln Crown Court', 'Lincoln Combined Court Centre', 'The Castle', 'Castle Hill', 'LN1 3GA', NULL, 'Lincoln', 'Lincolnshire', NULL, 'CRWCRT'),
('433', 'Liverpool Crown Court', 'QEII Law Courts', 'Derby Square', 'Liverpool', 'L2 1XA', NULL, 'Merseyside', NULL, NULL, 'CRWCRT'),
('434', 'Maidstone Crown Court', 'Maidstone Combined Court Centre', 'The Law Courts', 'Barker Road', 'ME16 8EQ', NULL, 'Maidstone', 'Kent', NULL, 'CRWCRT'),
('435', 'Manchester Crown Court', 'Courts of Justice', 'Crown Square', 'Manchester', 'M3 3FL', NULL, 'Greater Manchester', NULL, NULL, 'CRWCRT'),
('436', 'Minshull Street Manchester Crown Court', 'The Crown Court at Manchester', 'Minshull Street', 'Manchester', 'M1 3FS', NULL, 'Greater Manchester', NULL, NULL, 'CRWCRT'),
('437', 'Merthyr Tydfil Crown Court', 'Merthyr Tydfil Combined Crt Centre', 'The Law Courts', 'Glebeland Place', 'CF47 8BH', NULL, 'Merthyr Tydfil', 'South Wales', NULL, 'CRWCRT'),
('438', 'Mold Crown Court', 'The Law Courts', 'County Civic Centre', 'Mold', 'CH7 1AE', NULL, 'Flintshire', NULL, NULL, 'CRWCRT'),
('439', 'Newcastle upon Tyne Crown Court', 'Newcastle upon Tyne Combined Court', 'The Law Courts', 'Quayside', 'NE1 3LA', NULL, 'Newcastle upon Tyne', 'Tyne & Wear', NULL, 'CRWCRT'),
('440', 'Inner London Crown Court', 'Sessions House', 'Newington Causeway', 'London', 'SE1 6AZ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('441', 'Newport (South Wales) Crown Court', 'The Law Courts', 'Faulkner Road', 'Newport', 'NP20 4PR', NULL, 'Gwent', 'South Wales', NULL, 'CRWCRT'),
('442', 'Northampton Crown Court', 'Northampton Combined Court Centre', '85-87 Lady''s Lane', 'Northampton', 'NN1 3HQ', NULL, 'Northamptonshire', NULL, NULL, 'CRWCRT'),
('443', 'Norwich Crown Court', 'Norwich Combined Court Centre', 'The Law Courts', 'Bishopgate', 'NR3 1UR', NULL, 'Norwich', NULL, NULL, 'CRWCRT'),
('444', 'Nottingham Crown Court', 'The Law Courts', '60 Canal Street', 'Nottingham', 'NG1 7EL', NULL, NULL, NULL, NULL, 'CRWCRT'),
('445', 'Oxford Crown Court', 'Oxford Combined Court Centre', 'St. Aldates', 'Oxford', 'OX1 1TL', NULL, NULL, NULL, NULL, 'CRWCRT'),
('446', 'Plymouth Crown Court', 'The Law Courts', 'Armada Way', 'Plymouth', 'PL1 2ER', NULL, 'Devon', NULL, NULL, 'CRWCRT'),
('447', 'Portsmouth Crown Court', 'Portsmouth Combined Court Centre', 'The Courts of Justice', 'Winston Churchill Avenue', 'PO1 2EB', NULL, 'Portsmouth', 'Hampshire', NULL, 'CRWCRT'),
('448', 'Preston Crown Court', 'Preston Combined Court Centre', 'The Law Courts', 'Openshaw Place', 'PR1 2LL', NULL, 'Ring Way', 'Preston', NULL, 'CRWCRT'),
('449', 'Reading Crown Court', 'Old Shire Hall', 'The Forbury', 'Reading', 'RG1 3EH', NULL, 'Berkshire', NULL, NULL, 'CRWCRT'),
('450', 'St. Albans Crown Court', 'The Court Building', 'Bricket Road', 'St. Albans', 'AL1 3JW', NULL, 'Hertfordshire', NULL, NULL, 'CRWCRT'),
('451', 'Sheffield Crown Court', 'Sheffield Combined Court Centre', 'The Law Courts', '50 West Bar', 'S3 8PH', NULL, 'Sheffield', 'South Yorkshire', NULL, 'CRWCRT'),
('452', 'Shrewsbury Crown Court', 'Shrewsbury Justice Centre', 'Preston Street', 'Shrewsbury', 'SY2 5NX', NULL, 'Shropshire', NULL, NULL, 'CRWCRT'),
('453', 'Snaresbrook Crown Court', '75 Hollybush Hill', 'Snaresbrook', 'London', 'E11 1QW', NULL, NULL, NULL, NULL, 'CRWCRT'),
('454', 'Southampton Crown Court', 'Southampton Combined Court Centre', 'The Courts of Justice', 'London Road', 'SO15 2XQ', NULL, 'Southampton', 'Hampshire', NULL, 'CRWCRT'),
('455', 'Stafford Crown Court', 'Stafford Combined Court Centre', 'Victoria Square', 'Stafford', 'ST16 2QQ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('456', 'Stoke-on-Trent Crown Court', 'Stoke-on-Trent Combined Crt Centre', 'Bethesda Street', 'Hanley', 'ST1 3BP', NULL, 'Stoke-on-Trent', 'Staffordshire', NULL, 'CRWCRT'),
('457', 'Swansea Crown Court', 'The Law Courts', 'St. Helens Road', 'Swansea', 'SA1 4PF', NULL, 'South Wales', NULL, NULL, 'CRWCRT'),
('458', 'Swindon Crown Court', 'Swindon Combined Court Centre', 'The Law Courts', 'Islington Street', 'SN1 2HG', NULL, 'Swindon', 'Wiltshire', NULL, 'CRWCRT'),
('459', 'Taunton Crown Court', 'Shire Hall', 'Taunton', 'Somerset', 'TA1 4EU', NULL, NULL, NULL, NULL, 'CRWCRT'),
('460', 'Teesside Crown Court', 'Teesside Combined Court Centre', 'Centre Square', 'Middlesbrough', 'TS1 2AE', NULL, 'Cleveland', NULL, NULL, 'CRWCRT'),
('461', 'Basildon Crown Court', 'Basildon Combined Court', 'The Gore', 'Basildon', 'SS14 2EU', NULL, 'Essex', NULL, NULL, 'CRWCRT'),
('463', 'Warwick Crown Court sitting at Leamington Spa', 'Warwickshire Justice Centre', 'Newbold Terrace', 'LEAMINGTON SPA', 'CV32 4EL', NULL, 'Warwickshire', NULL, NULL, 'CRWCRT'),
('465', 'Winchester Crown Court', 'Winchester Combined Court Centre', 'The Law Courts', 'Winchester', 'SO23 9EL', NULL, 'Hampshire', NULL, NULL, 'CRWCRT'),
('466', 'Worcester Crown Court', 'Worcester Combined Court Centre', 'The Shirehall', 'Foregate Street', 'WR1 1EQ', NULL, 'Worcester', NULL, NULL, 'CRWCRT'),
('467', 'York Crown Court', 'The Castle', 'York', 'North Yorkshire', 'YO1 9WZ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('468', 'Harrow Crown Court', 'Hailsham Drive', 'Harrow', 'Middlesex', 'HA1 4TU', NULL, NULL, NULL, NULL, 'CRWCRT'),
('469', 'Wood Green Crown Court', 'Woodall House', 'Lordship Lane', 'Wood Green', 'N22 5LF', NULL, 'London', NULL, NULL, 'CRWCRT'),
('470', 'Bolton Crown Court', 'Bolton Combined Court Centre', 'The Law Courts', 'Blackhorse Street', 'BL1 1SU', NULL, 'Bolton', 'Greater Manchester', NULL, 'CRWCRT'),
('471', 'Southwark Crown Court', '1 English Grounds', '(Off Battlebridge Lane)', 'Southwark', 'SE1 2HU', NULL, 'London', NULL, NULL, 'CRWCRT'),
('472', 'Woolwich Crown Court', '2 Belmarsh Road', 'London', NULL, 'SE28 0EY', NULL, NULL, NULL, NULL, 'CRWCRT'),
('473', 'Peterborough Crown Court', 'Peterborough Combined Court Centre', 'Crown Buildings', 'Rivergate', 'PE1 1EJ', NULL, 'Peterborough', NULL, NULL, 'CRWCRT'),
('474', 'Guildford Crown Court', 'Bedford Road', 'Guildford', 'Surrey', 'GU1 4ST', NULL, NULL, NULL, NULL, 'CRWCRT'),
('475', 'Isleworth Crown Court', '36 Ridgeway Road', 'Isleworth', 'London', 'TW7 5LP', NULL, NULL, NULL, NULL, 'CRWCRT'),
('476', 'Luton Crown Court', '7 George Street', 'Luton', 'Bedfordshire', 'LU1 2AA', NULL, NULL, NULL, NULL, 'CRWCRT'),
('477', 'Truro Crown Court', 'Courts of Justice', 'Edward Street', 'Truro', 'TR1 2PB', NULL, 'Cornwall', NULL, NULL, 'CRWCRT'),
('478', 'Newport (I.O.W.) Crown Court', 'Isle of Wight Combined Court', '1 Quay Street', 'Newport', 'PO30 5YT', NULL, 'Isle of Wight', NULL, NULL, 'CRWCRT'),
('479', 'Canterbury Crown Court', 'Canterbury Combined Court Centre', 'The Law Courts', 'Chaucer Road', 'CT1 1ZA', NULL, 'Canterbury', 'Kent', NULL, 'CRWCRT'),
('480', 'Salisbury Crown Court', 'Salisbury Law Courts', 'Wilton Road', 'Salisbury', 'SP2 7EP', NULL, 'Wiltshire', NULL, NULL, 'CRWCRT'),
('750', 'Barnstaple Crown Court', 'The Civic Centre', 'Barnstaple', 'Devon', NULL, NULL, NULL, NULL, NULL, 'CRWCRT'),
('751', 'Barrow-in-Furness Crown Court', 'The Magistrates'' Court', 'Abbey Road', 'Barrow-in-Furness', 'LA14 5QX', NULL, 'Cumbria', NULL, NULL, 'CRWCRT'),
('754', 'Bury St. Edmunds Crown Court', 'Shire Hall', 'Bury St Edmunds', 'Suffolk', NULL, NULL, NULL, NULL, NULL, 'CRWCRT'),
('755', 'Caernarfon Crown Court', 'Caernarfon Criminal Justice Centre', 'Llanberis Road', 'Caernarfon', 'LL55 2DF', NULL, 'Gwynedd', NULL, NULL, 'CRWCRT'),
('756', 'Carmarthen Crown Court', 'The Guildhall', 'Carmarthen', NULL, NULL, NULL, NULL, NULL, NULL, 'CRWCRT'),
('758', 'Dolgellau Crown Court', 'The County Hall', 'Dolgellau', 'Gwynedd', NULL, NULL, NULL, NULL, NULL, 'CRWCRT'),
('761', 'Haverfordwest Crown Court', 'Penffynnon', 'Hawthorn Rise', 'Haverfordwest', 'SA61 3BQ', NULL, 'Dyfed', NULL, NULL, 'CRWCRT'),
('762', 'Hereford Crown Court', 'The Shirehall', 'St Peter''s Square', 'Hereford', 'HR1 2HY', NULL, 'Herefordshire', NULL, NULL, 'CRWCRT'),
('765', 'King''s Lynn Crown Court', 'The Court House', 'College Lane', 'King''s Lynn', 'PE30 1PQ', NULL, 'Norfolk', NULL, NULL, 'CRWCRT'),
('767', 'Knutsford Crown Court', 'The Sessions House', 'Toft Road', 'Knutsford, Cheshire', NULL, NULL, NULL, NULL, NULL, 'CRWCRT'),
('768', 'Lancaster Crown Court', 'The Castle', 'Lancaster', NULL, 'LA1 1YJ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('772', 'Southend Crown Court', 'The Court House', 'Victoria Avenue', 'Southend-on-Sea', 'SS2 6EG', NULL, 'Essex', NULL, NULL, 'CRWCRT'),
('774', 'Welshpool Crown Court', 'Town Hall', 'Welshpool', 'Powys', 'SY2 7TQ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('775', 'Warrington Crown Court', 'Warrington Combined Court Centre', 'Legh Street', 'Warrington', 'WA1 1UR', NULL, 'Cheshire', NULL, NULL, 'CRWCRT'),
('777', 'Amersham Crown Court', 'King George V Road', 'Amersham', 'Buckinghamshire', 'HP6 5AJ', NULL, NULL, NULL, NULL, 'CRWCRT'),
('778', 'Taunton Crown Court sitting at Worle', 'North Somerset Courthouse', 'The Hedges', 'St Georges', 'BS22 7BB', NULL, 'Weston-Super-Mare', NULL, NULL, 'CRWCRT'),
('1013', 'Bristol Magistrates'' Court', 'Marlborough Street', 'Bristol', NULL, 'BS1 3NU', NULL, NULL, NULL, NULL, 'PSA'),
('1021', 'North Avon Magistrates'' Court', 'Kennedy Way', 'Yate', 'South Gloucestershire', 'BS37 4PY', NULL, NULL, NULL, NULL, 'PSA'),
('1030', 'Somerset Magistrates'' Court', 'St John''s Road', 'Taunton', 'Somerset', 'TA1 4AX', NULL, NULL, NULL, NULL, 'PSA'),
('1080', 'Bedfordshire Magistrates'' Court', 'Stuart Street', 'Luton', 'Bedfordshire', 'LU1 5BL', NULL, NULL, NULL, NULL, 'PSA'),
('1247', 'Hartlepool Magistrates'' Court', 'The Law Courts', 'Victoria Road', 'Hartlepool', 'TS24 8BS', NULL, NULL, NULL, NULL, 'PSA'),
('1249', 'Teesside Magistrates'' Court', 'Teesside Law Courts', 'Victoria Square', 'Middlesbrough', 'TS1 2AS', NULL, NULL, NULL, NULL, 'PSA'),
('1300', 'North and East Devon Magistrates'' Court', 'Southernhay Gardens', 'Exeter', NULL, 'EX1 1UH', NULL, NULL, NULL, NULL, 'PSA'),
('1301', 'Cornwall Magistrates'' Court', 'The Magistrates'' Court', 'Launceston Road', 'Bodmin', 'PL31 2AL', NULL, 'Cornwall', NULL, NULL, 'PSA'),
('1302', 'South and West Devon Magistrates'' Court', 'Magistrates'' Court', 'St Andrew Street', 'Plymouth', 'PL1 2DP', NULL, NULL, NULL, NULL, 'PSA'),
('1304', 'West Hampshire Magistrates'' Court', 'The Court House', '100 The Avenue', 'Southampton', 'SO17 1EY', NULL, 'Hants.', NULL, NULL, 'PSA'),
('1305', 'North Hampshire Magistrates'' Court', 'The Court House', 'London Road', 'Basingstoke', 'RG21 4AB', NULL, 'Hants.', NULL, NULL, 'PSA'),
('1428', 'Southern Derbyshire Magistrates'' Court', 'Derby Justice Centre', 'St Mary''s Gate', 'Derby', 'DE1 3JR', NULL, 'Derbyshire', NULL, NULL, 'PSA'),
('1435', 'Northern Derbyshire Magistrates'' Court', 'Magistrates'' Court', 'Tapton Lane', 'Chesterfield', 'S41 7TW', NULL, 'Derbyshire', NULL, NULL, 'PSA'),
('1450', 'Avon & Somerset Magistrates'' Court', 'The Magistrates'' Court', 'Marlborough Street', 'Bristol', 'BS1 3NU', NULL, NULL, NULL, NULL, 'PSA'),
('1460', 'Cleveland Magistrates'' Court', 'Teesside Law Courts', 'Victoria Square', 'Middlesbrough', 'TS1 2AS', NULL, NULL, NULL, NULL, 'PSA'),
('1530', 'Dorset Magistrates'' Court', 'The Law Courts', 'Park Road', 'Poole', 'BH15 2NS', NULL, 'Dorset', NULL, NULL, 'PSA'),
('1585', 'County Durham and Darlington Magistrates'' Court', 'Magistrates'' Court', 'Central Avenue', 'Newton Aycliffe', 'DL5 5RT', NULL, 'Co. Durham', NULL, NULL, 'PSA'),
('1698', 'Gloucestershire Magistrates'' Courts', 'PO Box 9051', 'Gloucester', NULL, 'GL1 2XG', NULL, NULL, NULL, NULL, 'PSA'),
('1710', 'Cheshire Magistrates'' Court', 'Warrington Combined Court', 'Legh Street', 'Warrington', 'WA1 1UR', NULL, NULL, NULL, NULL, 'PSA'),
('1720', 'Greater Manchester Magistrates'' Court', 'Crown Square', 'Manchester', NULL, 'M60 1PR', NULL, NULL, NULL, NULL, 'PSA'),
('1721', 'South & East Cheshire Mags'' Ct', 'The Law Courts', 'Civic Centre, Crewe', 'Cheshire', 'CW1 2DT', NULL, NULL, NULL, NULL, 'PSA'),
('1722', 'North Cheshire Mags Court', 'Winmarleigh Street', 'Warrington', 'Cheshire', 'WA1 1PB', NULL, NULL, NULL, NULL, 'PSA'),
('1728', 'Sefton Magistrates'' Court', 'The Court House', 'Merton Road', 'Bootle, Merseyside', 'L20 3XX', NULL, NULL, NULL, NULL, 'PSA'),
('1729', 'West Cheshire Magistrates'' Crt', 'Chester Magistrates'' Court', 'Grosvenor Street', 'Chester', 'CH1 2XA', NULL, NULL, NULL, NULL, 'PSA'),
('1730', 'Liverpool & Knowsley Mags'' Crt', 'QEII Law Courts', 'Derby Square', 'Liverpool, Merseyside', 'L2 1XA', NULL, NULL, NULL, NULL, 'PSA'),
('1752', 'North and West Cumbria Magistrates'' Court', 'Nrth & West Cumbria Magistrates'' Ct', 'Rickergate', 'Carlisle', 'CA3 8QH', NULL, 'Cumbria', NULL, NULL, 'PSA'),
('1753', 'South Cumbria Magistrates'' Court', 'South Cumbria Magistrates'' Court', 'The Law Courts', 'Abbey Road', 'LA14 5QX', NULL, 'Barrow-in-Furness', 'Cumbria', NULL, 'PSA'),
('1782', 'Sth.East Hampshire Mags.Court', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth, Hants.', 'PO1 2DQ', NULL, NULL, NULL, NULL, 'PSA'),
('1783', 'Sth.Hampshire Mags.Court', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth, Hants.', 'PO1 2DQ', NULL, NULL, NULL, NULL, 'PSA'),
('1790', 'Lancashire Magistrates'' Court', 'The Law Courts', 'Lawson Street', 'Preston', 'PR1 2QT', NULL, 'Lancashire', NULL, NULL, 'PSA'),
('1800', 'East Hampshire Magistrates'' Court', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth', 'PO1 2DQ', NULL, 'Hants.', NULL, NULL, 'PSA'),
('1810', 'Merseyside Magistrates'' Court', 'QEII Law Courts', 'Derby Square', 'Liverpool', 'L2 1XA', NULL, 'Merseyside', NULL, NULL, 'PSA'),
('1841', 'Herefordshire Magistrates'' Court', 'The Court House', 'Castle Street', 'Worcester', 'WR1 3QZ', NULL, NULL, NULL, NULL, 'PSA'),
('1894', 'Worcestershire Magistrates'' Court', 'Worcester Justice Centre', 'Castle Street', 'Worcester', 'WR1 3QZ', NULL, NULL, NULL, NULL, 'PSA'),
('1903', 'North Lincolnshire Mags. Court', 'Court Centre Offices', 'Corporation Road', 'Scunthorpe, N. Lincs.', 'DN15 6QB', NULL, NULL, NULL, NULL, 'PSA'),
('1910', 'West and Central Hertfordshire Magistrates'' Court', 'Bedfordshire & Hertfordshire Admin', 'Luton & South Beds Magistrates'' Crt', 'Stuart Street', 'LU1 5BL', NULL, 'Luton', 'Bedfordshire', NULL, 'PSA'),
('1911', 'North and East Hertfordshire Magistrates'' Court', 'Bedfordshire & Hertfordshire Admin', 'Luton & South Beds Magistrates'' Crt', 'Stuart Street', 'LU1 5BL', NULL, 'Luton', 'Bedfordshire', NULL, 'PSA'),
('1920', 'Berkshire Magistrates'' Court', 'Civic Centre', 'Reading', 'Berkshire', 'RG1 7TQ', NULL, NULL, NULL, NULL, 'PSA'),
('1921', 'Buckinghamshire Magistrates'' Court', '301 Silbury Boulevard', 'Witan Gate East', 'Milton Keynes', 'MK9 2AJ', NULL, NULL, NULL, NULL, 'PSA'),
('1922', 'Oxfordshire Magistrates'' Court', 'The Court House', 'PO Box 37', 'Speedwell Street', 'OX1 1RZ', NULL, 'Oxford', NULL, NULL, 'PSA'),
('1940', 'Grimsby & Cleethorpes Mags Crt', 'Victoria Street', 'Grimsby', 'N.E. Lincs.', 'DN31 1PD', NULL, NULL, NULL, NULL, 'PSA'),
('1943', 'Hull & Holderness Mags. Court', 'Law Courts', 'PO Box 2, Market Place', 'Kingston-upon-Hull', 'HU1 2AD', NULL, NULL, NULL, NULL, 'PSA'),
('1945', 'Isle of Wight Magistrates'' Court', 'The Court House', 'Quay Street', 'Newport', 'PO30 5BB', NULL, 'Isle of Wight', NULL, NULL, 'PSA'),
('1949', 'Cambridgeshire Magistrates'' Court', 'Magistrates'' Court', 'Bridge Street', 'Peterborough', 'PE1 1ED', NULL, 'Cambridgeshire', NULL, NULL, 'PSA'),
('1960', 'Central Kent Magistrates'' Court', 'PO Box CH4', 'The Court House', 'The Brook', 'ME4 4JZ', NULL, 'Medway', 'Kent', NULL, 'PSA'),
('1965', 'East Kent Magistrates'' Courts', 'The Courthouse,', 'Castle Hill Avenue', 'Folkestone', 'CT20 2DH', NULL, 'Kent', NULL, NULL, 'PSA'),
('1966', 'North Kent Magistrates'' Court', 'PO Box CH4', 'The Court House', 'The Brook', 'ME4 4JZ', NULL, 'Medway', 'Kent', NULL, 'PSA'),
('1970', 'North Essex Magistrates'' Court', 'Osprey House', 'Hedgerows Business Park', 'Colchester Road', 'CM2 5PF', NULL, 'Springfield', 'Chelmsford', NULL, 'PSA'),
('1971', 'South Essex Magistrates'' Court', 'Osprey House', 'Hedgerows Business Park', 'Colchester Road', 'CM2 5PF', NULL, 'Springfield', 'Chelmsford', NULL, 'PSA'),
('1972', 'Norfolk Magistrates'' Court', 'The Court House', 'Bishopgate', 'Norwich', 'NR3 1UP', NULL, 'Norfolk', NULL, NULL, 'PSA'),
('1980', 'Humber Magistrates'' Court', 'Victoria Street', 'Grimsby', 'N.E. Lincs.', 'DN31 1PD', NULL, NULL, NULL, NULL, 'PSA'),
('2091', 'Northampton, Daventry and', 'Towcester Magistrates'' Court', 'Regent''s Pav'', Summerhouse Rd', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'PSA'),
('2095', 'Nottinghamshire Magistrates'' Court', 'Carrington Street', 'Nottingham', NULL, 'NG2 1EE', NULL, NULL, NULL, NULL, 'PSA'),
('2100', 'Leicester and Rutland Magistrates'' Court', '15 Pocklingtons Walk', 'Leicester', 'Leicestershire', 'LE1 6BT', NULL, NULL, NULL, NULL, 'PSA'),
('2105', 'Lincolnshire Magistrates'' Court', 'The Court House', '358 High Street', 'Lincoln', 'LN5 7QA', NULL, 'Lincolnshire', NULL, NULL, 'PSA'),
('2268', 'St. Helens Magistrates'' Court', 'QEII Law Courts', 'Derby Square', 'Liverpool, Merseyside', 'L2 1XA', NULL, NULL, NULL, NULL, 'PSA'),
('2271', 'Wirral Magistrates'' Court', 'The Sessions Courts', 'Chester Street', 'Birkenhead, Merseyside', 'CH41 5HW', NULL, NULL, NULL, NULL, 'PSA'),
('2321', 'Corby Magistrates'' Court', 'Regent''s Pavilion', 'Summerhouse Road', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'PSA'),
('2323', 'Kettering Magistrates'' Court', 'Regent''s Pavilion', 'Summerhouse Road', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'PSA'),
('2328', 'Wellingborough Mags. Court', 'Regent''s Pavilion', 'Summerhouse Road', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'PSA'),
('2330', 'Northamptonshire Magistrates'' Court', '85-87 Lady''s Lane', 'Northampton', 'Moulton Park, Northampton', 'NN1 3HQ', NULL, NULL, NULL, NULL, 'PSA'),
('2353', 'East Yorkshire Mags'' Court', 'Magistrates'' Clerk''s Office', 'Champney Road', 'Beverley, East Yorkshire', 'HU17 9EJ', NULL, NULL, NULL, NULL, 'PSA'),
('2354', 'Bradford & Keighley Mags. Crt', 'The Tyrls', 'Bradford', 'West Yorkshire', 'BD1 1LA', NULL, NULL, NULL, NULL, 'PSA'),
('2355', 'Wakefield&Pontefract Mags. Crt', 'The Court House', 'Cliff Parade', 'Wakefield, W.Yorks.', 'WF1 2TW', NULL, NULL, NULL, NULL, 'PSA'),
('2356', 'Kirklees Magistrates'' Court', 'The Court House', 'Civic Centre', 'Huddersfield, W.Yorks.', 'HD1 2NH', NULL, NULL, NULL, NULL, 'PSA'),
('2360', 'North Northumbria Magistrates'' Court', 'PO BOX 839', 'Market Street', 'Newcastle upon Tyne', 'NE99 1AU', NULL, NULL, NULL, NULL, 'PSA'),
('2365', 'South Northumbria Magistrates'' Court', 'Gateshead Law Courts', 'Warwick Street', 'Gateshead', 'NE8 1DT', NULL, 'Tyne & Wear', NULL, NULL, 'PSA'),
('2370', 'North Yorkshire Magistrates'' Court', 'Law Courts', 'Clifford Street', 'York', 'YO1 9RE', NULL, NULL, NULL, NULL, 'PSA'),
('2375', 'West Yorkshire Magistrates'' Court', 'PO Box 97', 'Westgate', 'Leeds', 'LS1 3JP', NULL, 'West Yorkshire', NULL, NULL, 'PSA'),
('2570', 'Central London Magistrates'' Court', '181 Marylebone Road', 'London', NULL, 'NW1 5BR', NULL, NULL, NULL, NULL, 'PSA'),
('2571', 'North West London Magistrates'' Court', 'Brent Magistrates Court', '448 High Road', 'London', 'NW10 2DZ', NULL, NULL, NULL, NULL, 'PSA'),
('2572', 'North London Magistrates'' Court', 'Highbury Corner Magistrates'' Court', '51 Holloway Road', 'London', 'N7 8JA', NULL, NULL, NULL, NULL, 'PSA'),
('2573', 'North East London Magistrates'' Court', '850 Cranbrook Road', 'Barkingside', 'Ilford', 'IG6 1HW', NULL, 'Essex', NULL, NULL, 'PSA'),
('2574', 'East London Magistrates'' Court', 'Thames Magistrates'' Court', '58 Bow Road', 'London', 'E3 4DJ', NULL, NULL, NULL, NULL, 'PSA'),
('2575', 'South East London Magistrates'' Court', 'Bromley Magistrates'' Court', 'London Road', 'Bromley', 'BR1 1RA', NULL, 'Kent', NULL, NULL, 'PSA'),
('2576', 'South London Magistrates'' Court', 'Camberwell Green Magistrates'' Court', '15 D''Eynsford Road', 'London', 'SE5 7UP', NULL, NULL, NULL, NULL, 'PSA'),
('2577', 'South West London Magistrates'' Court', 'Lavender Hill Magistrates'' Court', '176A Lavender Hill', 'London', 'SW11 1JU', NULL, NULL, NULL, NULL, 'PSA'),
('2578', 'West London Magistrates'' Court', 'West London Courthouse', '448 High Road', 'London', 'NW10 2DZ', NULL, NULL, NULL, NULL, 'PSA'),
('2770', 'Barnsley District Mags. Crt.', 'PO Box 17', 'Barnsley', 'S. Yorks.', 'S70 2DW', NULL, NULL, NULL, NULL, 'PSA'),
('2771', 'Doncaster Magistrates'' Court', 'PO Box 49', 'The Law Courts, College Road', 'Doncaster, S. Yorks', 'DN1 3HT', NULL, NULL, NULL, NULL, 'PSA'),
('2772', 'Rotherham Magistrates'' Court', 'The Law Courts', 'Castle Street', 'Sheffield, South Yorkshire', 'S3 8LU', NULL, NULL, NULL, NULL, 'PSA'),
('2773', 'Sheffield Magistrates'' Court', 'Castle Street', 'Sheffield', NULL, 'S3 8LU', NULL, NULL, NULL, NULL, 'PSA'),
('2791', 'North Staffordshire Mags'' Crt', 'The Court House, Ryecroft', 'Newcastle-under-Lyme', 'Staffordshire', 'ST5 2DG', NULL, NULL, NULL, NULL, 'PSA'),
('2799', 'Central & SW Staffs Mags'' Crt', 'The Court House', 'South Walls', 'Stafford', 'ST16 3DW', NULL, NULL, NULL, NULL, 'PSA'),
('2800', 'South Yorkshire Magistrates'' Court', 'The Law Courts', 'Castle Street', 'Sheffield', 'S3 8LU', NULL, 'South Yorkshire', NULL, NULL, 'PSA'),
('2805', 'Staffordshire Magistrates'' Court', 'Stafford Combined Court Centre', 'Victoria Square', 'Stafford', 'ST16 2QQ', NULL, 'Staffordshire', NULL, NULL, 'PSA'),
('2848', 'South West Surrey Mags. Court', 'PO Box 36', 'Guildford', 'Surrey', 'GU1 4AS', NULL, NULL, NULL, NULL, 'PSA'),
('2849', 'Nth. Surrey Magistrates'' Court', 'PO Box 5', 'The Law Courts', 'Knowle Green, Staines', 'TW18 1XR', NULL, NULL, NULL, NULL, 'PSA'),
('2856', 'SE Surrey Magistrates'' Court', 'The Law Courts', 'Hatchlands Road', 'Redhill, Surrey', 'RH1 6DH', NULL, NULL, NULL, NULL, 'PSA'),
('2860', 'SE Staffordshire Mags'' Court', 'The Court House', 'South Walls', 'Stafford', 'ST16 3DW', NULL, NULL, NULL, NULL, 'PSA'),
('2870', 'Suffolk Magistrates'' Court', 'Elm Street', 'Ipswich', 'Suffolk', 'IP1 2AP', NULL, NULL, NULL, NULL, 'PSA'),
('2875', 'Surrey Magistrates'' Court', 'Surrey Magistrates'' Court', 'Mary Road', 'Guildford', 'GU1 4PS', NULL, 'Surrey', NULL, NULL, 'PSA'),
('2905', 'Coventry and Warwickshire (Leamington) Magistrates'' Court', 'Warwickshire Justice Centre', 'Newbold Terrace', 'Leamington Spa', 'CV32 4EL', NULL, 'Warwickshire', NULL, NULL, 'PSA'),
('2922', 'Birmingham and Solihull Magistrates'' Court', 'Victoria Law Courts', 'Corporation Street', 'Birmingham', 'B4 6QA', NULL, NULL, NULL, NULL, 'PSA'),
('2923', 'Black Country Magistrates'' Court', 'The Inhedge', 'Dudley', NULL, 'DY1 1RY', NULL, NULL, NULL, NULL, 'PSA'),
('2924', 'Coventry and Warwickshire (Coventry) Magistrates'' Court', 'Little Park Street', 'Coventry', NULL, 'CV1 2SQ', NULL, NULL, NULL, NULL, 'PSA'),
('2948', 'Sussex (Eastern) Magistrates'' Court', 'The Law Courts', 'Horntye Park', 'Bohemia Road', 'TN34 1ND', NULL, 'Hastings', 'East Sussex', NULL, 'PSA'),
('2950', 'Sussex (Central) Magistrates'' Court', 'Brighton Magistrates'' Court', 'Edward Street', 'Brighton', 'BN2 0LG', NULL, 'East Sussex', NULL, NULL, 'PSA'),
('2951', 'West Sussex Magistrates'' Court', 'Sussex Magistrates'' Admin Centre', 'Edward Street', 'Brighton', 'BN2 0LG', NULL, 'East Sussex', NULL, NULL, 'PSA'),
('2992', 'Leeds District Mags. Court', 'PO Box 97', 'Westgate', 'Leeds, W. Yorks.', 'LS1 3JP', NULL, NULL, NULL, NULL, 'PSA'),
('2997', 'Calderdale Magistrates'' Court', 'PO Box 32', 'Harrison Road', 'Halifax, W. Yorks.', 'HX1 2AN', NULL, NULL, NULL, NULL, 'PSA'),
('3021', 'County of Wiltshire Magistrates'' Court', 'Princes Street', 'Swindon', 'Wiltshire', 'SN1 2JB', NULL, NULL, NULL, NULL, 'PSA'),
('3061', 'Denbighshire Mags. Court', 'Conwy Road', 'Llandudno', 'Conwy', 'LL30 1GA', NULL, NULL, NULL, NULL, 'PSA'),
('3062', 'Conwy Magistrates'' Court', 'Conwy Road', 'Llandudno', 'Conwy', 'LL30 1GA', NULL, NULL, NULL, NULL, 'PSA'),
('3063', 'North East Wales Magistrates'' Court', 'Mold Law Courts', 'Mold', 'Flintshire', 'CH7 1AE', NULL, NULL, NULL, NULL, 'PSA'),
('3070', 'North Central Wales Magistrates'' Court', 'The Law Courts', 'Conwy Road', 'Llandudno', 'LL30 1GA', NULL, 'Conwy', NULL, NULL, 'PSA'),
('3190', 'Cardiff Magistrates'' Court', 'Fitzalan Place', 'Cardiff', NULL, 'CF24 0RZ', NULL, NULL, NULL, NULL, 'PSA'),
('3211', 'Gwent Magistrates'' Court', 'Administration Department', 'The Law Courts', 'Faulkner Road', 'NP20 4PR', NULL, 'Newport', NULL, NULL, 'PSA'),
('3238', 'Anglesey Magistrates'' Court', 'Caernarfon Crim Justice Centre', 'Llanberis Road', 'Caernarfon, Gwynedd', 'LL55 2DF', NULL, NULL, NULL, NULL, 'PSA'),
('3240', 'North West Wales Magistrates'' Court', 'Caernarfon Criminal Justice Centre', 'Llanberis Road', 'Caernarfon', 'LL55 2DF', NULL, 'Gwynedd', NULL, NULL, 'PSA'),
('3244', 'Gwynedd Magistrates'' Court', 'Caernarfon Crim Justice Centre', 'Llanberis Road', 'Caernarfon, Gwynedd', 'LL55 2DF', NULL, NULL, NULL, NULL, 'PSA'),
('3246', 'Mid Wales (Llandrindod Wells) Magistrates'' Court', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'PSA'),
('3250', 'Brecknock & Radnorshire Mag Ct', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'PSA'),
('3251', 'Cardiff & Vale of Glamorgan', 'Magistrates'' Court', 'Fitzalan Place', 'Cardiff', 'CF24 0RZ', NULL, NULL, NULL, NULL, 'PSA'),
('3252', 'Carmarthenshire Magistrates'' Court', 'Town Hall Square', 'Llanelli', 'Carmarthenshire', 'SA15 3AW', NULL, NULL, NULL, NULL, 'PSA'),
('3253', 'Ceredigion and Pembrokeshire Magistrates'' Court', 'Aberystwyth Justice Centre', 'Y Lanfa', 'Trefechan', 'SY23 1AS', NULL, 'Aberystwyth', NULL, NULL, 'PSA'),
('3260', 'Mid Wales (Merthyr Tydfil) Magistrates'' Court', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'PSA'),
('3266', 'Newcastle & Ogmore Mags'' Court', 'Sunnyside', 'Bridgend', NULL, 'CF31 4AJ', NULL, NULL, NULL, NULL, 'PSA'),
('3270', 'Glamorgan Valleys Mags'' Court', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'PSA'),
('3285', 'Shropshire Magistrates'' Court', 'Telford Magistrates'' Court', 'Malinsgate', 'Telford', 'TF3 4HX', NULL, NULL, NULL, NULL, 'PSA'),
('3319', 'West Glamorgan Magistrates'' Court', 'Grove Place', 'Swansea', NULL, 'SA1 5DB', NULL, NULL, NULL, NULL, 'PSA'),
('3355', 'Montgomeryshire Magistrates'' Court', 'Mansion House', '24 Severn Street', 'Welshpool', 'SY21 7UX', NULL, 'Powys', NULL, NULL, 'PSA'),
('5013', 'Bristol Youth Court', 'Marlborough Street', 'Bristol', NULL, 'BS1 3NU', NULL, NULL, NULL, NULL, 'YCT'),
('5021', 'North Avon Youth Court', 'Kennedy Way', 'Yate', 'South Gloucestershire', 'BS37 4PY', NULL, NULL, NULL, NULL, 'YCT'),
('5030', 'Somerset Youth Court', 'St John''s Road', 'Taunton', 'Somerset', 'TA1 4AX', NULL, NULL, NULL, NULL, 'YCT'),
('5080', 'Bedfordshire Youth Court', 'Stuart Street', 'Luton', 'Bedfordshire', 'LU1 5BL', NULL, NULL, NULL, NULL, 'YCT'),
('5247', 'Hartlepool Youth Court', 'The Law Courts', 'Victoria Road', 'Hartlepool', 'TS24 8BS', NULL, NULL, NULL, NULL, 'YCT'),
('5249', 'Teesside Youth Court', 'Teesside Law Courts', 'Victoria Square', 'Middlesbrough', 'TS1 2AS', NULL, NULL, NULL, NULL, 'YCT'),
('5300', 'North and East Devon Youth Court', 'Southernhay Gardens', 'Exeter', NULL, 'EX1 1UH', NULL, NULL, NULL, NULL, 'YCT'),
('5301', 'Cornwall Youth Court', 'The Magistrates'' Court', 'Launceston Road', 'Bodmin', 'PL31 2AL', NULL, 'Cornwall', NULL, NULL, 'YCT'),
('5302', 'South and West Devon Youth Court', 'Magistrates'' Court', 'St Andrew Street', 'Plymouth', 'PL1 2DP', NULL, NULL, NULL, NULL, 'YCT'),
('5304', 'West Hampshire Youth Court', 'The Court House', '100 The Avenue', 'Southampton', 'SO17 1EY', NULL, 'Hants.', NULL, NULL, 'YCT'),
('5305', 'North Hampshire Youth Court', 'The Court House', 'London Road', 'Basingstoke', 'RG21 4AB', NULL, 'Hants.', NULL, NULL, 'YCT'),
('5428', 'Southern Derbyshire Youth Court', 'Derby Justice Centre', 'St Mary''s Gate', 'Derby', 'DE1 3JR', NULL, 'Derbyshire', NULL, NULL, 'YCT'),
('5435', 'Northern Derbyshire Youth Court', 'Magistrates'' Court', 'Tapton Lane', 'Chesterfield', 'S41 7TW', NULL, 'Derbyshire', NULL, NULL, 'YCT'),
('5450', 'Avon & Somerset Youth Court', 'The Magistrates'' Court', 'Marlborough Street', 'Bristol', 'BS1 3NU', NULL, NULL, NULL, NULL, 'YCT'),
('5460', 'Cleveland Youth Court', 'Teesside Law Courts', 'Victoria Square', 'Middlesbrough', 'TS1 2AS', NULL, NULL, NULL, NULL, 'YCT'),
('5530', 'Dorset Youth Court', 'The Law Courts', 'Park Road', 'Poole', 'BH15 2NS', NULL, 'Dorset', NULL, NULL, 'YCT'),
('5585', 'County Durham and Darlington Youth Court', 'Magistrates'' Court', 'Central Avenue', 'Newton Aycliffe', 'DL5 5RT', NULL, 'Co. Durham', NULL, NULL, 'YCT'),
('5698', 'Gloucestershire Youth Court', 'PO Box 9051', 'Gloucester', NULL, 'GL1 2XG', NULL, NULL, NULL, NULL, 'YCT'),
('5710', 'Cheshire Youth Court', 'Warrington Combined Court', 'Legh Street', 'Warrington', 'WA1 1UR', NULL, NULL, NULL, NULL, 'YCT'),
('5720', 'Greater Manchester Youth Court', 'Crown Square', 'Manchester', NULL, 'M60 1PR', NULL, NULL, NULL, NULL, 'YCT'),
('5721', 'South & East Cheshire Youth Ct', 'The Law Courts', 'Civic Centre, Crewe', 'Cheshire', 'CW1 2DT', NULL, NULL, NULL, NULL, 'YCT'),
('5722', 'North Cheshire Youth Court', 'Winmarleigh Street', 'Warrington', 'Cheshire', 'WA1 1PB', NULL, NULL, NULL, NULL, 'YCT'),
('5728', 'Sefton Youth Court', 'The Court House', 'Merton Road', 'Bootle, Merseyside', 'L20 3XX', NULL, NULL, NULL, NULL, 'YCT'),
('5729', 'West Cheshire Youth Court', 'Chester Magistrates'' Court', 'Grosvenor Street', 'Chester', 'CH1 2XA', NULL, NULL, NULL, NULL, 'YCT'),
('5730', 'Liverpool & Knowsley Youth Crt', 'QEII Law Courts', 'Derby Square', 'Liverpool, Merseyside', 'L2 1XA', NULL, NULL, NULL, NULL, 'YCT'),
('5752', 'North and West Cumbria Youth Court', 'North and West Cumbria Youth Crt', 'Rickergate', 'Carlisle', 'CA3 8QH', NULL, 'Cumbria', NULL, NULL, 'YCT'),
('5753', 'South Cumbria Youth Court', 'South Cumbria Magistrates'' Court', 'The Law Courts', 'Abbey Road', 'LA14 5QX', NULL, 'Barrow-in-Furness', 'Cumbria', NULL, 'YCT'),
('5782', 'South East Hampshire Youth Crt', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth, Hants.', 'PO1 2DQ', NULL, NULL, NULL, NULL, 'YCT'),
('5783', 'South Hampshire Youth Court', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth, Hants.', 'PO1 2DQ', NULL, NULL, NULL, NULL, 'YCT'),
('5790', 'Lancashire Youth Court', 'The Law Courts', 'Lawson Street', 'Preston', 'PR1 2QT', NULL, 'Lancashire', NULL, NULL, 'YCT'),
('5800', 'East Hampshire Youth Court', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth', 'PO1 2DQ', NULL, 'Hants.', NULL, NULL, 'YCT'),
('5810', 'Merseyside Youth Court', 'QEII Law Courts', 'Derby Square', 'Liverpool', 'L2 1XA', NULL, 'Merseyside', NULL, NULL, 'YCT'),
('5841', 'Herefordshire Youth Court', 'The Court House', 'Castle Street', 'Worcester', 'WR1 3QZ', NULL, NULL, NULL, NULL, 'YCT'),
('5894', 'Worcestershire Youth Court', 'Worcester Justice Centre', 'Castle Street', 'Worcester', 'WR1 3QZ', NULL, NULL, NULL, NULL, 'YCT'),
('5903', 'North Lincolnshire Youth Court', 'Court Centre Offices', 'Corporation Road', 'Scunthorpe, N. Lincs.', 'DN15 6QB', NULL, NULL, NULL, NULL, 'YCT'),
('5910', 'West and Central Hertfordshire Youth Court', 'Bedfordshire & Hertfordshire Admin', 'Luton & South Beds Magistrates'' Crt', 'Stuart Street', 'LU1 5BL', NULL, 'Luton', 'Bedfordshire', NULL, 'YCT'),
('5911', 'North and East Hertfordshire Youth Court', 'Bedfordshire & Hertfordshire Admin', 'Luton & South Beds Magistrates'' Crt', 'Stuart Street', 'LU1 5BL', NULL, 'Luton', 'Bedfordshire', NULL, 'YCT'),
('5920', 'Berkshire Youth Court', 'Civic Centre', 'Reading', 'Berkshire', 'RG1 7TQ', NULL, NULL, NULL, NULL, 'YCT'),
('5921', 'Buckinghamshire Youth Court', '301 Silbury Boulevard', 'Witan Gate East', 'Milton Keynes', 'MK9 2AJ', NULL, NULL, NULL, NULL, 'YCT'),
('5922', 'Oxfordshire Youth Court', 'The Court House', 'PO Box 37', 'Speedwell Street', 'OX1 1RZ', NULL, 'Oxford', NULL, NULL, 'YCT'),
('5940', 'Grimsby & Cleethorpes Yth Crt', 'Victoria Street', 'Grimsby', 'N.E. Lincs.', 'DN31 1PD', NULL, NULL, NULL, NULL, 'YCT'),
('5943', 'Hull & Holderness Youth Court', 'Law Courts, PO Box 2', 'Market Place', 'Kingston-upon-Hull', 'HU1 2AD', NULL, NULL, NULL, NULL, 'YCT'),
('5945', 'Isle of Wight Youth Court', 'The Court House', 'Quay Street', 'Newport', 'PO30 5BB', NULL, 'Isle of Wight', NULL, NULL, 'YCT'),
('5949', 'Cambridgeshire Youth Court', 'Magistrates'' Court', 'Bridge Street', 'Peterborough', 'PE1 1ED', NULL, 'Cambridgeshire', NULL, NULL, 'YCT'),
('5960', 'Central Kent Youth Court', 'PO Box CH4', 'The Court House', 'The Brook', 'ME4 4JZ', NULL, 'Medway', 'Kent', NULL, 'YCT'),
('5965', 'East Kent Youth Court', 'The Courthouse,', 'Castle Hill Avenue', 'Folkestone', 'CT20 2DH', NULL, 'Kent', NULL, NULL, 'YCT'),
('5966', 'North Kent Youth Court', 'PO Box CH4', 'The Court House', 'The Brook', 'ME4 4JZ', NULL, 'Medway', 'Kent', NULL, 'YCT'),
('5970', 'North Essex Youth Court', 'Osprey House', 'Hedgerows Business Park', 'Colchester Road', 'CM2 5PF', NULL, 'Springfield', 'Chelmsford', NULL, 'YCT'),
('5971', 'South Essex Youth Court', 'Osprey House', 'Hedgerows Business Park', 'Colchester Road', 'CM2 5PF', NULL, 'Springfield', 'Chelmsford', NULL, 'YCT'),
('5972', 'Norfolk Youth Court', 'The Court House', 'Bishopgate', 'Norwich', 'NR3 1UP', NULL, 'Norfolk', NULL, NULL, 'YCT'),
('5980', 'Humber Youth Court', 'Victoria Street', 'Grimsby', 'N.E. Lincs.', 'DN31 1PD', NULL, NULL, NULL, NULL, 'YCT'),
('6091', 'Northampton, Daventry and', 'Towcester Youth Court', 'Regent''s Pav'', Summerhouse Rd', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'YCT'),
('6095', 'Nottinghamshire Youth Court', 'Carrington Street', 'Nottingham', NULL, 'NG2 1EE', NULL, NULL, NULL, NULL, 'YCT'),
('6100', 'Leicester and Rutland Youth Court', '15 Pocklingtons Walk', 'Leicester', 'Leicestershire', 'LE1 6BT', NULL, NULL, NULL, NULL, 'YCT'),
('6105', 'Lincolnshire Youth Court', 'The Court House', '358 High Street', 'Lincoln', 'LN5 7QA', NULL, 'Lincolnshire', NULL, NULL, 'YCT'),
('6268', 'St. Helens Youth Court', 'QEII Law Courts', 'Derby Square', 'Liverpool, Merseyside', 'L2 1XA', NULL, NULL, NULL, NULL, 'YCT'),
('6271', 'Wirral Youth Court', 'The Sessions Courts', 'Chester Street', 'Birkenhead, Merseyside', 'CH41 5HW', NULL, NULL, NULL, NULL, 'YCT'),
('6323', 'Kettering Youth Court', 'Regent''s Pavilion', 'Summerhouse Road', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'YCT'),
('6328', 'Wellingborough Youth Court', 'Regent''s Pavilion', 'Summerhouse Road', 'Moulton Park, Northampton', 'NN3 6AS', NULL, NULL, NULL, NULL, 'YCT'),
('6330', 'Northamptonshire Youth Court', '85-87 Lady''s Lane', 'Northampton', 'Moulton Park, Northampton', 'NN1 3HQ', NULL, NULL, NULL, NULL, 'YCT'),
('6353', 'East Yorkshire Youth Court', 'Magistrates'' Clerk''s Office', 'Champney Road', 'Beverley, East Yorkshire', 'HU17 9EJ', NULL, NULL, NULL, NULL, 'YCT'),
('6354', 'Bradford & Keighley Youth Crt', 'The Tyrls', 'Bradford', 'West Yorkshire', 'BD1 1LA', NULL, NULL, NULL, NULL, 'YCT'),
('6355', 'Wakefield&Pontefract Youth Crt', 'The Court House', 'Cliff Parade', 'Wakefield, W.Yorks.', 'WF1 2TW', NULL, NULL, NULL, NULL, 'YCT'),
('6356', 'Kirklees Youth Court', 'The Court House', 'Civic Centre', 'Huddersfield, W.Yorks.', 'HD1 2NH', NULL, NULL, NULL, NULL, 'YCT'),
('6360', 'North Northumbria Youth Court', 'PO BOX 839', 'Market Street', 'Newcastle upon Tyne', 'NE99 1AU', NULL, NULL, NULL, NULL, 'YCT'),
('6365', 'South Northumbria Youth Court', 'Law Courts', 'Gillbridge Avenue', 'Sunderland', 'SR1 3AP', NULL, NULL, NULL, NULL, 'YCT'),
('6370', 'North Yorkshire Youth Court', 'Law Courts', 'Clifford Street', 'York', 'YO1 9RE', NULL, NULL, NULL, NULL, 'YCT'),
('6375', 'West Yorkshire Youth Court', 'PO Box 97', 'Westgate', 'Leeds', 'LS1 3JP', NULL, 'West Yorkshire', NULL, NULL, 'YCT'),
('6570', 'Central London Youth Court', '181 Marylebone Road', 'London', NULL, 'NW1 5BR', NULL, NULL, NULL, NULL, 'YCT'),
('6571', 'North West London Youth Court', 'Brent Magistrates'' Court', '448 High Road', 'London', 'NW10 2DZ', NULL, NULL, NULL, NULL, 'YCT'),
('6572', 'North London Youth Court', 'Highbury Corner Magistrates'' Court', '51 Holloway Road', 'London', 'N7 8JA', NULL, NULL, NULL, NULL, 'YCT'),
('6573', 'North East London Youth Court', '850 Cranbrook Road', 'Barkingside', 'Ilford', 'IG6 1HW', NULL, 'Essex', NULL, NULL, 'YCT'),
('6574', 'East London Youth Court', 'Thames Magistrates'' Court', '58 Bow Road', 'London', 'E3 4DJ', NULL, NULL, NULL, NULL, 'YCT'),
('6575', 'South East London Youth Court', 'Bromley Magistrates'' Court', 'London Road', 'Bromley', 'BR1 1RA', NULL, 'Kent', NULL, NULL, 'YCT'),
('6576', 'South London Youth Court', 'Croydon Magistrates'' Court', 'Barclay Road', 'Croydon', 'CR9 3NG', NULL, 'Surrey', NULL, NULL, 'YCT'),
('6577', 'South West London Youth Court', 'Lavender Hill Magistrates'' Court', '176A Lavender Hill', 'London', 'SW11 1JU', NULL, NULL, NULL, NULL, 'YCT'),
('6578', 'West London Youth Court', 'West London Courthouse', '448 High Road', 'London', 'NW10 2DZ', NULL, NULL, NULL, NULL, 'YCT'),
('6700', 'Inner London Family Proceedings Court', 'First Avenue House', '42-49 High Holborn', 'London', 'WC1V 6NP', NULL, NULL, NULL, NULL, 'PSA'),
('6770', 'Barnsley District Youth Court', 'PO Box 17', 'Barnsley', 'S. Yorks', 'S70 2DW', NULL, NULL, NULL, NULL, 'YCT'),
('6771', 'Doncaster Youth Court', 'PO Box 49, The Law Courts', 'College Road', 'Doncaster, S. Yorks.', 'DN1 3HT', NULL, NULL, NULL, NULL, 'YCT'),
('6772', 'Rotherham Youth Court', 'The Law Courts', 'Castle Street', 'Sheffield, South Yorkshire', 'S3 8LU', NULL, NULL, NULL, NULL, 'YCT'),
('6773', 'Sheffield Youth Court', 'Castle Street', 'Sheffield', NULL, 'S3 8LU', NULL, NULL, NULL, NULL, 'YCT'),
('6791', 'North Staffordshire Youth Crt', 'The Court House, Ryecroft', 'Newcastle-under-Lyme', 'Staffordshire', 'ST5 2DG', NULL, NULL, NULL, NULL, 'YCT'),
('6799', 'Central & SW Staffs Youth Crt', 'The Court House', 'South Walls', 'Stafford', 'ST16 3DW', NULL, NULL, NULL, NULL, 'YCT'),
('6800', 'South Yorkshire Youth Court', 'The Law Courts', 'Castle Street', 'Sheffield', 'S3 8LU', NULL, 'South Yorkshire', NULL, NULL, 'YCT'),
('6805', 'Staffordshire Youth Court', 'Stafford Combined Court Centre', 'Victoria Square', 'Stafford', 'ST16 2QQ', NULL, 'Staffordshire', NULL, NULL, 'YCT'),
('6848', 'South West Surrey Youth Court', 'PO Box 36', 'Guildford', 'Surrey', 'GU1 4AS', NULL, NULL, NULL, NULL, 'YCT'),
('6849', 'North Surrey Youth Court', 'PO Box 5, The Law Courts', 'Knowle Green, Staines', 'Middlesex', 'TW18 1XR', NULL, NULL, NULL, NULL, 'YCT'),
('6856', 'South East Surrey Youth Court', 'The Law Courts', 'Hatchlands Road', 'Redhill, Surrey', 'RH1 6DH', NULL, NULL, NULL, NULL, 'YCT'),
('6860', 'SE Staffordshire Youth Court', 'The Court House', 'South Walls', 'Stafford', 'ST16 3DW', NULL, NULL, NULL, NULL, 'YCT'),
('6870', 'Suffolk Youth Court', 'Elm Street', 'Ipswich', 'Suffolk', 'IP1 2AP', NULL, NULL, NULL, NULL, 'YCT'),
('6875', 'Surrey Youth Court', 'Surrey Magistrates'' Court', 'Mary Road', 'Guildford', 'GU1 4PS', NULL, 'Surrey', NULL, NULL, 'YCT'),
('6905', 'Coventry and Warwickshire (Leamington) Youth Court', 'Warwickshire Justice Centre', 'Newbold Terrace', 'Leamington Spa', 'CV32 4EL', NULL, 'Warwickshire', NULL, NULL, 'YCT'),
('6922', 'Birmingham and Solihull Youth Court', 'Victoria Law Courts', 'Corporation Street', 'Birmingham', 'B4 6QA', NULL, NULL, NULL, NULL, 'YCT'),
('6923', 'Black Country Youth Court', 'The Inhedge', 'Dudley', NULL, 'DY1 1RY', NULL, NULL, NULL, NULL, 'YCT'),
('6924', 'Coventry and Warwickshire (Coventry) Youth Court', 'Little Park Street', 'Coventry', NULL, 'CV1 2SQ', NULL, NULL, NULL, NULL, 'YCT'),
('6948', 'Sussex (Eastern) Youth Court', 'The Law Courts', 'Horntye Park', 'Bohemia Road', 'TN34 1ND', NULL, 'Hastings', 'East Sussex', NULL, 'YCT'),
('6950', 'Sussex (Central) Youth Court', 'Brighton Magistrates'' Court', 'Edward Street', 'Brighton', 'BN2 0LG', NULL, 'East Sussex', NULL, NULL, 'YCT'),
('6951', 'West Sussex Youth Court', 'Sussex Magistrates'' Admin Centre', 'Edward Street', 'Brighton', 'BN2 0LG', NULL, 'East Sussex', NULL, NULL, 'YCT'),
('6992', 'Leeds District Youth Court', 'PO Box 97', 'Westgate, Leeds', 'West Yorks', 'LS1 3JP', NULL, NULL, NULL, NULL, 'YCT'),
('6997', 'Calderdale Youth Court', 'PO Box 32', 'Harrison Road', 'Halifax, W. Yorks.', 'HX1 2AN', NULL, NULL, NULL, NULL, 'YCT'),
('7021', 'County of Wiltshire Youth Court', 'Princes Street', 'Swindon', 'Wiltshire', 'SN1 2JB', NULL, NULL, NULL, NULL, 'YCT'),
('7061', 'Denbighshire Youth Court', 'Conwy Road', 'Llandudno', 'Conwy', 'LL30 1GA', NULL, NULL, NULL, NULL, 'YCT'),
('7062', 'Conwy Youth Court', 'Conwy Road', 'Llandudno', 'Conwy', 'LL30 1GA', NULL, NULL, NULL, NULL, 'YCT'),
('7063', 'North East Wales Youth Court', 'Mold Law Courts', 'Mold', 'Flintshire', 'CH7 1AE', NULL, NULL, NULL, NULL, 'YCT'),
('7070', 'North Central Wales Youth Court', 'The Law Courts', 'Conwy Road', 'Llandudno', 'LL30 1GA', NULL, 'Conwy', NULL, NULL, 'YCT'),
('7190', 'Cardiff Youth Court', 'Fitzalan Place', 'Cardiff', NULL, 'CF24 0RZ', NULL, NULL, NULL, NULL, 'YCT'),
('7211', 'Gwent Youth Court', 'Administration Department', 'The Law Courts', 'Faulkner Road', 'NP20 4PR', NULL, 'Newport', NULL, NULL, 'YCT'),
('7238', 'Anglesey Youth Court', 'Caernarfon Crim. Justice Cnt', 'Llanberis Road, Caernarfon', 'Gwynedd', 'LL55 2DF', NULL, NULL, NULL, NULL, 'YCT'),
('7240', 'North West Wales Youth Court', 'Caernarfon Criminal Justice Centre', 'Llanberis Road', 'Caernarfon', 'LL55 2DF', NULL, 'Gwynedd', NULL, NULL, 'YCT'),
('7244', 'Gwynedd Youth Court', 'Caernarfon Crim. Justice Cnt', 'Llanberis Rd, Caernarfon', 'Gwynedd', 'LL55 2DF', NULL, NULL, NULL, NULL, 'YCT'),
('7246', 'Mid Wales (Llandrindod Wells) Youth Court', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'YCT'),
('7250', 'Brecknock & Radnorshire Yth Ct', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'YCT'),
('7251', 'Cardiff & Vale of Glamorgan', 'Youth Court', 'Fitzalan Place', 'Cardiff', 'CF24 0RZ', NULL, NULL, NULL, NULL, 'YCT'),
('7252', 'Carmarthenshire Youth Court', 'Town Hall Square', 'Llanelli', 'Carmarthenshire', 'SA15 3AW', NULL, NULL, NULL, NULL, 'YCT'),
('7253', 'Ceredigion and Pembrokeshire Youth Court', 'Aberystwyth Justice Centre', 'Y Lanfa', 'Trefechan', 'SY23 1AS', NULL, 'Aberystwyth', NULL, NULL, 'YCT'),
('7260', 'Mid Wales (Merthyr Tydfil) Youth Court', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'YCT'),
('7266', 'Newcastle & Ogmore Youth Court', 'Sunnyside', 'Bridgend', NULL, 'CF31 4AJ', NULL, NULL, NULL, NULL, 'YCT'),
('7270', 'Glamorgan Valleys Youth Court', 'The Law Courts', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', NULL, NULL, NULL, NULL, 'YCT'),
('7285', 'Shropshire Youth Court', 'Telford Magistrates'' Court', 'Malinsgate', 'Telford', 'TF3 4HX', NULL, NULL, NULL, NULL, 'YCT'),
('7319', 'West Glamorgan Youth Court', 'Grove Place', 'Swansea', NULL, 'SA1 5DB', NULL, NULL, NULL, NULL, 'YCT'),
('7355', 'Montgomeryshire Youth Court', 'Mansion House', '24 Severn Street', 'Welshpool', 'SY21 7UX', NULL, 'Powys', NULL, NULL, 'YCT'),
('9001', 'Antrim Magistrates'' Court', 'The Courthouse', '30 Castle Way', 'Antrim', 'BA41 4AQ', NULL, NULL, NULL, NULL, 'NICRT'),
('9002', 'Ards Magistrates'' Court', 'The Courthouse', 'Regent Street', 'Newtonards', 'BT23 4LP', NULL, NULL, NULL, NULL, 'NICRT'),
('9003', 'Armagh Magistrates'' Court', 'The Courthouse', 'The Mall', 'Armagh', 'BT61 9DJ', NULL, NULL, NULL, NULL, 'NICRT'),
('9004', 'Ballymena Magistrates'' Court', 'The Courthouse', 'Albert Place', 'Ballymena', 'BT43 6DY', NULL, 'Co. Antrim', NULL, NULL, 'NICRT'),
('9006', 'Banbridge Magistrates'' Court', 'The Courthouse', 'Victoria Street', 'Banbridge', 'BT32 3DH', NULL, NULL, NULL, NULL, 'NICRT'),
('9007', 'Belfast and Newtownabbey Magistrates'' Court', 'Laganside Courts', '45 Oxford Street', 'Belfast', 'BT1 3LL', NULL, NULL, NULL, NULL, 'NICRT'),
('9012', 'Castlereagh Magistrates'' Court', 'The Courthouse', 'Regent Street', 'Newtownards', 'BT23 4LP', NULL, NULL, NULL, NULL, 'NICRT'),
('9015', 'East Tyrone Magistrates'' Court', 'The Courthouse', '46 Killyman Road', 'Dungannon', 'BT71 6FG', NULL, NULL, NULL, NULL, 'NICRT'),
('9016', 'Craigavon Magistrates'' Court', 'The Courthouse', 'Central Way', 'Craigavon', 'BT64 1AP', NULL, NULL, NULL, NULL, 'NICRT'),
('9018', 'Down Magistrates'' Court', 'The Courthouse', 'English Street', 'Downpatrick', 'BT30 6AD', NULL, NULL, NULL, NULL, 'NICRT'),
('9020', 'Fermanagh Magistrates'' Court', 'The Courthouse', 'East Bridge Street`', 'Enniskillen', 'BT74 7BP', NULL, NULL, NULL, NULL, 'NICRT'),
('9024', 'Larne Magistrates'' Court', 'The Courthouse', 'Victoria Road', 'Larne', 'BT40 1RN', NULL, NULL, NULL, NULL, 'NICRT'),
('9025', 'Limavady Magistrates'' Court', 'The Courthouse', 'Main Street', 'Limavady', 'BT49 0EY', NULL, NULL, NULL, NULL, 'NICRT'),
('9026', 'Lisburn Magistrates'' Court', 'The Courthouse', 'Railway Street', 'Lisburn', 'BT28 1XR', NULL, NULL, NULL, NULL, 'NICRT'),
('9028', 'Londonderry Magistrates'' Court', 'The Courthouse', 'Bishop Street', 'Londonderry', 'BT48 6PQ', NULL, NULL, NULL, NULL, 'NICRT'),
('9029', 'Magherafelt Magistrates'' Court', 'The Courthouse', 'Hospital Road', 'Magherafelt', 'BT45 5DG', NULL, NULL, NULL, NULL, 'NICRT'),
('9030', 'North Antrim Magistrates'' Court', 'The Courthouse', '46A Mountsandel Road', 'Coleraine', 'BT52 1NY', NULL, 'Co. Londonderry', NULL, NULL, 'NICRT'),
('9032', 'Newry and Mourne Magistrates'' Court', 'The Courthouse', '23 New Street', 'Newry', 'BT35 6JD', NULL, NULL, NULL, NULL, 'NICRT'),
('9034', 'North Down Magistrates'' Court', 'The Courthouse', '6 Quay Street', 'Bangor', 'BT20 5EA', NULL, NULL, NULL, NULL, 'NICRT'),
('9035', 'Omagh Magistrates'' Court', 'The Courthouse', 'High Street', 'Omagh', 'BT78 1DU', NULL, NULL, NULL, NULL, 'NICRT'),
('9036', 'Strabane Magistrates'' Court', 'The Courthouse', 'Derry Road', 'Strabane', 'BT82 8DT', NULL, NULL, NULL, NULL, 'NICRT'),
('9201', 'Court of Appeal', 'Royal Courts of Justice', 'Strand', 'London', 'WC2A 2LL', NULL, NULL, NULL, NULL, 'CRWCRT'),
('9240', 'Alloa JP Court', 'Sheriff Court House', '47 Drysdale Street', 'Alloa', 'FK10 1JA', NULL, NULL, NULL, NULL, 'SJCRT'),
('9246', 'Dumfries JP Court', 'Sheriff Court House', 'Buccleuch Street', 'Dumfries', 'DG1 2AN', NULL, NULL, NULL, NULL, 'SJCRT'),
('9250', 'Stranraer JP Court', 'Sheriff Court House', 'Lewis Street', 'Stranraer', 'DG9 7AA', NULL, NULL, NULL, NULL, 'SJCRT'),
('9251', 'Aberdeen JP Court', 'Sheriff Court House', 'Castle Street', 'Aberdeen', 'AB10 1WP', NULL, NULL, NULL, NULL, 'SJCRT'),
('9252', 'Banff JP Court', 'Sheriff Court House', 'Low Street', 'Banff', 'AB45 1AU', NULL, NULL, NULL, NULL, 'SJCRT'),
('9253', 'Peterhead JP Court', 'Sheriff Court House', 'Queen Street', 'Peterhead', 'AB42 1TP', NULL, NULL, NULL, NULL, 'SJCRT'),
('9256', 'Dundee JP Court', 'Sheriff Court House', '6 West Bell Street', 'Dundee', 'DD1 9AD', NULL, NULL, NULL, NULL, 'SJCRT'),
('9261', 'Kilmarnock JP Court', 'Sheriff Court House', 'St Marnock Street', 'Kilmarnock', 'KA1 1ED', NULL, NULL, NULL, NULL, 'SJCRT'),
('9264', 'Forfar JP Court', 'Sheriff Court House', 'Market Street', 'Forfar', 'DD8 3LA', NULL, NULL, NULL, NULL, 'SJCRT'),
('9278', 'Edinburgh JP Court', 'Sheriff Court House', '27 Chambers Street', 'Edinburgh', 'EH1 1LB', NULL, NULL, NULL, NULL, 'SJCRT'),
('9282', 'Falkirk JP Court', 'Sheriff Court House', 'Main Street', 'Camelon', 'FK1 4AR', NULL, 'Falkirk', NULL, NULL, 'SJCRT'),
('9286', 'Dunfermline JP Court', 'Sheriff Court House', '1-6 Carnegie Drive', 'Dunfermline', 'KY12 7HJ', NULL, NULL, NULL, NULL, 'SJCRT'),
('9287', 'Kirkcaldy JP Court', 'Sheriff Court House', 'Whytescauseway', 'Kirkcaldy', 'KY1 1XQ', NULL, NULL, NULL, NULL, 'SJCRT'),
('9289', 'Campbeltown JP Court', 'Sheriff Court House', 'Castlehill', 'Campbeltown', 'PA28 6AN', NULL, NULL, NULL, NULL, 'SJCRT'),
('9290', 'Dunoon JP Court', 'Sheriff Court House', 'George Street', 'Dunoon', 'PA23 8BQ', NULL, 'Argyll', NULL, NULL, 'SJCRT'),
('9292', 'Lochgilphead JP Court', 'Sheriff Court House', 'George Street', 'Dunoon', 'PA23 8BQ', NULL, NULL, NULL, NULL, 'SJCRT'),
('9293', 'Oban JP Court', 'Sheriff Court House', 'Albany Street', 'Oban', 'PA34 4AL', NULL, NULL, NULL, NULL, 'SJCRT'),
('9295', 'Glasgow JP Court', 'Sheriff Clerk''s Office', 'PO Box 23', '1 Carlton Place', 'G5 9DA', NULL, 'Glasgow', NULL, NULL, 'SJCRT'),
('9340', 'Greenock JP Court', 'Sheriff Court House', '1 Nelson Street', 'Greenock', 'PA15 1TR', NULL, NULL, NULL, NULL, 'SJCRT'),
('9341', 'Elgin JP Court', 'Sheriff Court House', 'High Street', 'Elgin', 'IV30 1BU', NULL, NULL, NULL, NULL, 'SJCRT'),
('9342', 'Paisley JP Court', 'Sheriff Court House', 'St James Street', 'Paisley', 'PA3 2HW', NULL, NULL, NULL, NULL, 'SJCRT'),
('9345', 'Fort William JP Court', 'Sheriff Court House', 'High Street', 'Fort William', 'PH33 6EE', NULL, NULL, NULL, NULL, 'SJCRT'),
('9346', 'Inverness Justice of the Peace Court', 'The Inverness Justice Centre', 'Longman Road', 'Inverness', 'IV1 1AH', NULL, NULL, NULL, NULL, 'SJCRT'),
('9348', 'Tain JP Court', 'Sheriff Court House', 'High Street', 'Tain', 'IV19 1AB', NULL, NULL, NULL, NULL, 'SJCRT'),
('9351', 'Jedburgh JP Court', 'Sheriff Court House', 'Castlegate', 'Jedburgh', 'TD8 6AR', NULL, NULL, NULL, NULL, 'SJCRT'),
('9353', 'Selkirk JP Court', 'Sheriff Court House', 'Ettrick Terrace', 'Selkirk', 'TD7 4LE', NULL, NULL, NULL, NULL, 'SJCRT'),
('9355', 'Coatbridge JP Court', '453 Main Street', 'Coatbridge', NULL, 'ML5 3RS', NULL, NULL, NULL, NULL, 'SJCRT'),
('9358', 'Perth JP Court', 'Sheriff Court House', 'Tay Street', 'Perth', 'PH2 8NL', NULL, NULL, NULL, NULL, 'SJCRT'),
('9360', 'Ayr JP Court', 'Sheriff Court House', 'Wellington Square', 'Ayr', 'KA7 1EE', NULL, NULL, NULL, NULL, 'SJCRT'),
('9366', 'Hamilton JP Court', 'Sheriff Court House', '4 Beckford Street', 'Hamilton', 'ML3 0BT', NULL, NULL, NULL, NULL, 'SJCRT'),
('9367', 'Lanark JP Court', 'Sheriff Court House', '24 Hope Street', 'Lanark', 'ML11 7NE', NULL, NULL, NULL, NULL, 'SJCRT'),
('9372', 'Stirling JP Court', 'Sheriff Court House', 'Viewfield Place', 'Stirling', 'FK8 1NH', NULL, NULL, NULL, NULL, 'SJCRT'),
('9376', 'Dumbarton JP Court', 'Sheriff Court House', 'Church Street', 'Dumbarton', 'G82 1QR', NULL, NULL, NULL, NULL, 'SJCRT'),
('9380', 'Livingston JP Court', 'Sheriff Court House', 'West Lothian Civic Centre', 'Howden South Road', 'EH54 6FF', NULL, 'Livingston', NULL, NULL, 'SJCRT'),
('9701', 'Aberdeen Sheriff Court District', 'Sheriff Court House', 'Castle Street', 'Aberdeen', 'AB10 1WP', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9702', 'Airdrie Sheriff Court District', 'Sheriff Court House', 'Graham Street', 'Airdrie', 'ML6 6EE', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9703', 'Alloa Sheriff Court District', 'Sheriff Court House', '47 Drysdale Street', 'Alloa', 'FK10 1JA', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9704', 'Ayr Sheriff Court District', 'Sheriff Court House', 'Wellington Square', 'Ayr', 'KA7 1EE', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9711', 'Banff Sheriff Court District', 'Sheriff Court House', 'Low Street', 'Banff', 'AB45 1AU', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9716', 'Campbeltown Sheriff Court District', 'Sheriff Court House', 'Castlehill', 'Campbeltown', 'PA28 6AN', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9723', 'Dumbarton Sheriff Court District', 'Sheriff Court House', 'Church Street', 'Dumbarton', 'G82 1QR', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9724', 'Dumfries Sheriff Court District', 'Sheriff Court House', 'Buccleuch Street', 'Dumfries', 'DG1 2AN', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9726', 'Dundee Sheriff Court District', 'Sheriff Court House', '6 West Bell Street', 'Dundee', 'DD1 9AD', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9727', 'Dunfermline Sheriff Court District', 'Sheriff Court House', '1-6 Carnegie Drive', 'Dunfermline', 'KY12 7HJ', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9728', 'Dunoon Sheriff Court District', 'Sheriff Court House', 'George Street', 'Dunoon', 'PA23 8BQ', NULL, 'Argyll', NULL, NULL, 'SCSCRT'),
('9741', 'Edinburgh Sheriff Court District', 'Sheriff Court House', '27 Chambers Street', 'Edinburgh', 'EH1 1LB', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9742', 'Elgin Sheriff Court District', 'Sheriff Court House', 'High Street', 'Elgin', 'IV30 1BU', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9751', 'Falkirk Sheriff Court District', 'Sheriff Court House', 'Main Street', 'Camelon', 'FK1 4AR', NULL, 'Falkirk', NULL, NULL, 'SCSCRT'),
('9752', 'Forfar Sheriff Court District', 'Sheriff Court House', 'Market Street', 'Forfar', 'DD8 3LA', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9753', 'Fort William Sheriff Court District', 'Sheriff Court House', 'High Street', 'Fort William', 'PH33 6EE', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9761', 'Glasgow and Strathkelvin Sheriff Court', 'Sheriff Court House', 'PO Box 23', '1 Carlton Place', 'G5 9DA', NULL, 'Glasgow', NULL, NULL, 'SCSCRT'),
('9762', 'Greenock Sheriff Court District', 'Sheriff Court House', '1 Nelson Street', 'Greenock', 'PA15 1TR', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9772', 'Hamilton Sheriff Court District', 'Sheriff Court House', '4 Beckford Street', 'Hamilton', 'ML3 0BT', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9781', 'Inverness Sheriff Court District', 'The Inverness Justice Centre', 'Longman Road', 'Inverness', 'IV1 1AH', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9791', 'Jedburgh Sheriff Court District', 'Sheriff Court House', 'Castlegate', 'Jedburgh', 'TD8 6AR', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9801', 'Kilmarnock Sheriff Court District', 'Sheriff Court House', 'St Marnock Street', 'Kilmarnock', 'KA1 1ED', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9803', 'Kirkcaldy Sheriff Court District', 'Sheriff Court House', 'Whytescauseway', 'Kirkcaldy', 'KY1 1XQ', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9805', 'Kirkwall Sheriff Court District', 'Sheriff Court House', 'Watergate', 'Kirkwall', 'KW15 1PD', NULL, 'Orkney', NULL, NULL, 'SCSCRT'),
('9811', 'Lanark Sheriff Court District', 'Sheriff Court House', '24 Hope Street', 'Lanark', 'ML11 7NE', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9812', 'Lerwick Sheriff Court District', 'Sheriff Court House', 'King Erik Street', 'Lerwick', 'ZE1 0HD', NULL, 'Shetland', NULL, NULL, 'SCSCRT'),
('9814', 'Lochmaddy Sheriff Court District', 'Sheriff Court House', 'Lochmaddy', 'Isle of North Uist', 'HS6 5AE', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9815', 'Livingston Sheriff Court District', 'Sheriff Court House', 'West Lothian Civic Centre', 'Howden South Road', 'EH54 6FF', NULL, 'Livingston', NULL, NULL, 'SCSCRT'),
('9841', 'Oban Sheriff Court District', 'Sheriff Court House', 'Albany Street', 'Oban', 'PA34 4AL', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9851', 'Paisley Sheriff Court District', 'Sheriff Court House', 'St. James Street', 'Paisley', 'PA3 2HW', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9853', 'Perth Sheriff Court District', 'Sheriff Court House', 'Tay Street', 'Perth', 'PH2 8NL', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9854', 'Peterhead Sheriff Court District', 'Sheriff Court House', 'Queen Street', 'Peterhead', 'AB42 1TP', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9855', 'Portree Sheriff Court District', 'Sheriff Court House', 'Somerled Square', 'Portree', 'IV51 9EH', NULL, 'Isle of Skye', NULL, NULL, 'SCSCRT'),
('9871', 'Selkirk Sheriff Court District', 'Sheriff Court House', 'Ettrick Terrace', 'Selkirk', 'TD7 4LE', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9872', 'Stirling Sheriff Court District', 'Sheriff Court House', 'Viewfield Place', 'Stirling', 'FK8 1NH', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9874', 'Stornoway Sheriff Court District', 'Sheriff Court House', '9 Lewis Street', 'Stornoway', 'HS1 9JF', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9875', 'Stranraer Sheriff Court District', 'Sheriff Court House', 'Lewis Street', 'Stranraer', 'DG9 7AA', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9881', 'Tain Sheriff Court District', 'Sheriff Court House', 'High Street', 'Tain', 'IV19 1AB', NULL, NULL, NULL, NULL, 'SCSCRT'),
('9891', 'Wick Sheriff Court District', 'Sheriff Court House', 'Bridge Street', 'Wick', 'KW1 4AJ', NULL, 'Caithness', NULL, NULL, 'SCSCRT'),
('9985', 'Asylum & Immigration Tribunal', 'Arnhem Support Centre', 'PO Box 6987', 'Leicester', 'LE1 6ZX', NULL, NULL, NULL, NULL, 'PSA'),
('9986', 'Central Authority for MRFP', 'London Collection & Compliance Ctr', 'MRFP', 'DX 154264', NULL, NULL, 'Southwark 12', NULL, NULL, 'PSA'),
('9999', 'Default LJA', 'Default', NULL, NULL, 'Default', NULL, NULL, NULL, NULL, 'PSA');