/**
* CGI OPAL Program
*
* MODULE      : exported_lja_inserts.sql
*
* DESCRIPTION : The insert statements generated using pgAdmin Postgres from Reference Data CSV files to be used to populate the local_justice_areas table in the Fines model
*
* VERSION HISTORY:
*
* Date          Author      Version     Nature of Change
* ----------    -------     --------    ----------------------------------------------------------------------------------------------------------------------------------
* 05/05/2024    A Dennis    1.0         PO-305 The insert statements generated using pgAdmin Postgres from CSV files to be used to populate the offences table Fines model
*
**/
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4163, 'County Durham and Darlington Magistrates'' Court', 'Magistrates'' Court', 'Central Avenue', 'Newton Aycliffe', 'DL5 5RT', '1585', 'Co. Durham', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4165, 'Bedfordshire Magistrates'' Court', 'Stuart Street', 'Luton', 'Bedfordshire', 'LU1 5BL', '1080', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5004, 'Birmingham and Solihull Magistrates'' Court', 'Victoria Law Courts', 'Corporation Street', 'Birmingham', 'B4 6QA', '2922', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5005, 'Coventry and Warwickshire (Coventry) Magistrates'' Court', 'Little Park Street', 'Coventry', NULL, 'CV1 2SQ', '2924', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5006, 'Black Country Magistrates'' Court', 'The Inhedge', 'Dudley', NULL, 'DY1 1RY', '2923', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5010, 'Coventry and Warwickshire (Leamington) Magistrates'' Court', 'Warwickshire Justice Centre', 'Newbold Terrace', 'Leamington Spa', 'CV32 4EL', '2905', 'Warwickshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5012, 'Nottinghamshire Magistrates'' Court', 'Carrington Street', 'Nottingham', NULL, 'NG2 1EE', '2095', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5014, 'Lincolnshire Magistrates'' Court', 'The Court House', '358 High Street', 'Lincoln', 'LN5 7QA', '2105', 'Lincolnshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5016, 'Leicester and Rutland Magistrates'' Court', '15 Pocklingtons Walk', 'Leicester', 'Leicestershire', 'LE1 6BT', '2100', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5194, 'Worcestershire Magistrates'' Court', 'Worcester Justice Centre', 'Castle Street', 'Worcester', 'WR1 3QZ', '1894', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5195, 'Shropshire Magistrates'' Court', 'Telford Magistrates'' Court', 'Malinsgate', 'Telford', 'TF3 4HX', '3285', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5198, 'Northern Derbyshire Magistrates'' Court', 'Magistrates'' Court', 'Tapton Lane', 'Chesterfield', 'S41 7TW', '1435', 'Derbyshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5200, 'West Glamorgan Magistrates'' Court', 'Grove Place', 'Swansea', NULL, 'SA1 5DB', '3319', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (1814, 'Southern Derbyshire Magistrates'' Court', 'Derby Justice Centre', 'St Mary''s Gate', 'Derby', 'DE1 3JR', '1428', 'Derbyshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5572, 'North Northumbria Magistrates'' Court', 'PO BOX 839', 'Market Street ', 'Newcastle upon Tyne', 'NE99 1AU', '2360', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5573, 'South Northumbria Magistrates'' Court', 'Gateshead Law Courts', 'Warwick Street', 'Gateshead', 'NE8 1DT', '2365', 'Tyne & Wear', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5576, 'North Yorkshire Magistrates'' Court', 'Law Courts', 'Clifford Street', 'York', 'YO1 9RE', '2370', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3098, 'Gloucestershire Magistrates'' Courts', 'PO Box 9051', 'Gloucester', NULL, 'GL1 2XG', '1698', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3119, 'North Kent Magistrates'' Court', 'PO Box CH4', 'The Court House', 'The Brook', 'ME4 4JZ', '1966', 'Medway', 'Kent', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3123, 'Central Kent Magistrates'' Court', 'PO Box CH4', 'The Court House', 'The Brook', 'ME4 4JZ', '1960', 'Medway', 'Kent', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5000, 'County of Wiltshire Magistrates'' Court', 'Princes Street', 'Swindon', 'Wiltshire', 'SN1 2JB', '3021', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5204, 'North and West Cumbria Magistrates'' Court', 'Nrth & West Cumbria Magistrates'' Ct', 'Rickergate', 'Carlisle', 'CA3 8QH', '1752', 'Cumbria', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5205, 'South Cumbria Magistrates'' Court', 'South Cumbria Magistrates'' Court', 'The Law Courts', 'Abbey Road', 'LA14 5QX', '1753', 'Barrow-in-Furness', 'Cumbria', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5208, 'Suffolk Magistrates'' Court', 'Elm Street ', 'Ipswich', 'Suffolk', 'IP1 2AP', '2870', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5210, 'North East Wales Magistrates'' Court', 'Mold Law Courts', 'Mold', 'Flintshire', 'CH7 1AE', '3063', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5715, 'Merseyside Magistrates'' Court', 'QEII Law Courts', 'Derby Square', 'Liverpool', 'L2 1XA', '1810', 'Merseyside', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5717, 'Cheshire Magistrates'' Court', 'Warrington Combined Court', 'Legh Street', 'Warrington', 'WA1 1UR', '1710', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5719, 'West Yorkshire Magistrates'' Court', 'PO Box 97 ', 'Westgate', 'Leeds', 'LS1 3JP', '2375', 'West Yorkshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5721, 'South Yorkshire Magistrates'' Court', 'The Law Courts', 'Castle Street', 'Sheffield', 'S3 8LU', '2800', 'South Yorkshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5723, 'Humber Magistrates'' Court', 'Victoria Street', 'Grimsby', 'N.E. Lincs.', 'DN31 1PD', '1980', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5725, 'Cleveland Magistrates'' Court', 'Teesside Law Courts', 'Victoria Square', 'Middlesbrough', 'TS1 2AS', '1460', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5727, 'Staffordshire Magistrates'' Court', 'Stafford Combined Court Centre', 'Victoria Square', 'Stafford', 'ST16 2QQ', '2805', 'Staffordshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5729, 'Northamptonshire Magistrates'' Court', 'Regent''s Pavilion', 'Summerhouse Road', 'Moulton Park', 'NN3 6AS', '2330', 'Northampton', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5731, 'East Hampshire Magistrates'' Court', 'The Law Courts', 'Winston Churchill Avenue', 'Portsmouth', 'PO1 2DQ', '1800', 'Hants.', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5733, 'Surrey Magistrates'' Court', 'Surrey Magistrates'' Court', 'Mary Road', 'Guildford', 'GU1 4PS', '2875', 'Surrey ', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5735, 'Avon & Somerset Magistrates'' Court', 'The Magistrates'' Court', 'Marlborough Street', 'Bristol', 'BS1 3NU', '1450', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5737, 'North Central Wales Magistrates'' Court', 'The Law Courts', 'Conwy Road', 'Llandudno', 'LL30 1GA', '3070', 'Conwy', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5739, 'North West Wales Magistrates'' Court', 'Caernarfon Criminal Justice Centre', 'Llanberis Road', 'Caernarfon', 'LL55 2DF', '3240', 'Gwynedd', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5741, 'Cardiff Magistrates'' Court', 'Fitzalan Place', 'Cardiff', NULL, 'CF24 0RZ', '3190', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5743, 'Mid Wales (Merthyr Tydfil) Magistrates'' Court', 'The Law Courts ', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', '3260', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5745, 'Mid Wales (Llandrindod Wells) Magistrates'' Court', 'The Law Courts ', 'Glebeland Place', 'Merthyr Tydfil', 'CF47 8BU', '3246', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3864, 'Central Authority for MRFP', 'London Collection & Compliance Ctr', 'MRFP', 'DX 154264', NULL, '9986', 'Southwark 12', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3865, 'Asylum & Immigration Tribunal', 'Arnhem Support Centre', 'PO Box 6987', 'Leicester', 'LE1 6ZX', '9985', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3866, 'Montgomeryshire Magistrates'' Court', 'Mansion House', '24 Severn Street', 'Welshpool', 'SY21 7UX', '3355', 'Powys', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (2052, 'Inner London Family Proceedings Court', 'First Avenue House', '42-49 High Holborn', 'London', 'WC1V 6NP', '6700', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (2126, 'Isle of Wight Magistrates'' Court', 'The Court House', 'Quay Street', 'Newport', 'PO30 5BB', '1945', 'Isle of Wight', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3190, 'Gwent Magistrates'' Court', 'Administration Department', 'The Law Courts', 'Faulkner Road', 'NP20 4PR', '3211', 'Newport', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4047, 'North East London Magistrates'' Court', '850 Cranbrook Road', 'Barkingside', 'Ilford', 'IG6 1HW', '2573', 'Essex', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4048, 'Central London Magistrates'' Court', '181 Marylebone Road', 'London', NULL, 'NW1 5BR', '2570', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4049, 'South East London Magistrates'' Court', 'Bromley Magistrates'' Court', 'London Road', 'Bromley', 'BR1 1RA', '2575', 'Kent', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4050, 'South West London Magistrates'' Court', 'Lavender Hill Magistrates'' Court', '176A Lavender Hill', 'London', 'SW11 1JU', '2577', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4051, 'East London Magistrates'' Court', 'Thames Magistrates'' Court', '58 Bow Road', 'London', 'E3 4DJ', '2574', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4052, 'South London Magistrates'' Court', 'Camberwell Green Magistrates'' Court', '15 D''Eynsford Road', 'London', 'SE5 7UP', '2576', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4053, 'North London Magistrates'' Court', 'Highbury Corner Magistrates'' Court', '51 Holloway Road', 'London', 'N7 8JA', '2572', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4054, 'West London Magistrates'' Court', 'West London Courthouse', '448 High Road', 'London', 'NW10 2DZ', '2578', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4055, 'North West London Magistrates'' Court', 'Brent Magistrates Court', '448 High Road', 'London', 'NW10 2DZ', '2571', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4115, 'Norfolk Magistrates'' Court', 'The Court House', 'Bishopgate', 'Norwich', 'NR3 1UP', '1972', 'Norfolk', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4117, 'North and East Hertfordshire Magistrates'' Court', 'Bedfordshire & Hertfordshire Admin', 'Luton & South Beds Magistrates'' Crt', 'Stuart Street', 'LU1 5BL', '1911', 'Luton', 'Bedfordshire', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4118, 'West and Central Hertfordshire Magistrates'' Court', 'Bedfordshire & Hertfordshire Admin', 'Luton & South Beds Magistrates'' Crt', 'Stuart Street', 'LU1 5BL', '1910', 'Luton', 'Bedfordshire', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4121, 'South Essex Magistrates'' Court', 'Osprey House', 'Hedgerows Business Park', 'Colchester Road', 'CM2 5PF', '1971', 'Springfield', 'Chelmsford', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4122, 'North Essex Magistrates'' Court', 'Osprey House', 'Hedgerows Business Park', 'Colchester Road', 'CM2 5PF', '1970', 'Springfield', 'Chelmsford', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4125, 'Berkshire Magistrates'' Court', 'Civic Centre', 'Reading', 'Berkshire', 'RG1 7TQ', '1920', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4127, 'Oxfordshire Magistrates'' Court', 'The Court House', 'PO Box 37 ', 'Speedwell Street', 'OX1 1RZ', '1922', 'Oxford', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4131, 'West Hampshire Magistrates'' Court', 'The Court House', '100 The Avenue', 'Southampton', 'SO17 1EY', '1304', 'Hants.', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4132, 'North Hampshire Magistrates'' Court', 'The Court House', 'London Road', 'Basingstoke', 'RG21 4AB', '1305', 'Hants.', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4135, 'Cornwall Magistrates'' Court', 'The Magistrates'' Court', 'Launceston Road', 'Bodmin', 'PL31 2AL', '1301', 'Cornwall', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4136, 'South and West Devon Magistrates'' Court', 'Magistrates'' Court', 'St Andrew Street', 'Plymouth', 'PL1 2DP', '1302', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4137, 'North and East Devon Magistrates'' Court', 'Southernhay Gardens', 'Exeter', NULL, 'EX1 1UH', '1300', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4147, 'Carmarthenshire Magistrates'' Court', 'Town Hall Square', 'Llanelli', 'Carmarthenshire', 'SA15 3AW', '3252', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4148, 'Ceredigion and Pembrokeshire Magistrates'' Court', 'Aberystwyth Justice Centre', 'Y Lanfa', 'Trefechan', 'SY23 1AS', '3253', 'Aberystwyth', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5212, 'Cambridgeshire Magistrates'' Court', 'Magistrates'' Court', 'Bridge Street', 'Peterborough', 'PE1 1ED', '1949', 'Cambridgeshire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5214, 'Dorset Magistrates'' Court', 'The Law Courts', 'Park Road', 'Poole', 'BH15 2NS', '1530', 'Dorset', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5578, 'Lancashire Magistrates'' Court', 'The Law Courts', 'Lawson Street', 'Preston', 'PR1 2QT', '1790', 'Lancashire', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5580, 'Greater Manchester Magistrates'' Court', 'Crown Square', 'Manchester', NULL, 'M60 1PR', '1720', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (5582, 'West Sussex Magistrates'' Court', 'Sussex Magistrates'' Admin Centre', 'Edward Street', 'Brighton', 'BN2 0LG', '2951', 'East Sussex', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (2530, 'Sussex (Central) Magistrates'' Court', 'Brighton Magistrates'' Court', 'Edward Street', 'Brighton', 'BN2 0LG', '2950', 'East Sussex', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (4126, 'Buckinghamshire Magistrates'' Court', '301 Silbury Boulevard', 'Witan Gate East', 'Milton Keynes', 'MK9 2AJ', '1921', NULL, NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (3217, 'East Kent Magistrates'' Courts', 'The Courthouse, ', 'Castle Hill Avenue', 'Folkestone', 'CT20 2DH', '1965', 'Kent', NULL, NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (2540, 'Sussex (Eastern) Magistrates'' Court', 'The Law Courts', 'Horntye Park', 'Bohemia Road', 'TN34 1ND', '2948', 'Hastings', 'East Sussex', NULL);
INSERT INTO local_justice_areas (local_justice_area_id, name, address_line_1, address_line_2, address_line_3, postcode, lja_code, address_line_4, address_line_5, end_date) VALUES (2619, 'Herefordshire Magistrates'' Court', 'The Court House', 'Castle Street', 'Worcester', 'WR1 3QZ', '1841', NULL, NULL, NULL);
