/**
* OPAL Program
*
* MODULE      : insert_documents.sql
*
* DESCRIPTION : Insert data into DOCUMENTS table
*
* VERSION HISTORY:
*
* Date          Author       Version     Nature of Change
* ----------    --------     --------    ---------------------------------------------------------------------------------------------------------
* 16/06/2025    C Cho        1.0         PO-1880 Insert reference data for documents
*
**/


/* sourced from Libra/GoB */
DELETE FROM result_documents;
DELETE FROM documents;

INSERT INTO documents (document_id,recipient,document_language,priority,header_type,signature_source,document_template,document_elements,print_parameters) VALUES
('CHEQUE','CRED','EN',0,NULL,NULL,'1_0','[{ "data_item":"cheque", "sequence":1, "language_dependent":false }]','[{ "name":"cheque_number", "type":"integer", "min":0, "max":9999999999 }]'),
('CTSLIP','DEF','EN',0,NULL,NULL,'1_0','[{ "data_item":"ctslip", "sequence":1, "language_dependent":false }]','[{ "name":"slip_number", "type":"integer", "min":0, "max":9999999999 }]'),
('ABD','BENA','EN',0,'EO','Area','25_0','[{ "name":"jobcentreaddress", "sequence":15, "data_item":"procaddress", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"amountoutstanding", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"defendantindefault", "sequence":35, "data_item":"defindefault", "language_dependent":false },{ "name":"ninumber", "sequence":40, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"offences", "sequence":100, "data_item":"accountoffpen", "language_dependent":false }]',NULL),
('ABDD','DEF','EN',0,'EO','Area','25_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"ninumber", "sequence":15, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"amountoutstanding", "sequence":20, "data_item":"accountbalance", "language_dependent":false },{ "name":"offences", "sequence":100, "data_item":"accountoffpen", "language_dependent":false }]',NULL),
('AEOF','EMP','EN',0,'EO','Area','46_0','[{ "name":"employeeaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"ninumber", "sequence":30, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"totaloutstanding", "sequence":35, "data_item":"accountbalance", "language_dependent":false },{ "name":"gobterminalentries", "sequence":40, "data_item":"resultentries", "language_dependent":false },{ "name":"bankdetails", "sequence":45, "data_item":"accountctbankdetail", "language_dependent":false },{ "name":"webempdet", "sequence":50, "data_item":"caseemploymentdets", "language_dependent":false },{ "name":"gobempdet", "sequence":55, "data_item":"accountemploydets", "language_dependent":false }]',NULL),
('AEOFD','DEF','EN',0,'EO','Area','45_0','[{ "name":"employeeaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"ninumber", "sequence":20, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"totaloutstanding", "sequence":30, "data_item":"accountbalance", "language_dependent":false },{ "name":"gobterminalentries", "sequence":35, "data_item":"resultentries", "language_dependent":false },{ "name":"webempdet", "sequence":40, "data_item":"caseemploymentdets", "language_dependent":false },{ "name":"gobempdet", "sequence":45, "data_item":"accountemploydets", "language_dependent":false }]',NULL),
('AEOLD','DEF','EN',0,'EO','LJA','45_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"lumpsumoutstanding", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"gobterminalentries", "sequence":45, "data_item":"resultentries", "language_dependent":false },{ "name":"webempdet", "sequence":50, "data_item":"caseemploymentdets", "language_dependent":false },{ "name":"gobempdet", "sequence":55, "data_item":"accountemploydets", "language_dependent":false }]',NULL),
('BACKLET','DEF','EN',1,'EO','Area','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"warrantnumber", "sequence":15, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"amountenforced", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"warrantcontactdetails", "sequence":30, "data_item":"accountwarrantcont", "language_dependent":false }]',NULL),
('BACKLETDW','DEF','EN',2,'EO','Area','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"dwdays", "sequence":30, "data_item":"ctdwdays", "language_dependent":false }]',NULL),
('CERTBR','PRIS','EN',0,'A','Area','20_0','[{ "name":"prisonaddress", "sequence":5, "data_item":"prisondetail", "language_dependent":false },{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false }]',NULL),
('CLAMPO','DEF','EN',0,'EO','Area','44_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"moneyowed", "sequence":15, "data_item":"accountbalance", "language_dependent":false },{ "name":"contractoraddress", "sequence":25, "data_item":"procaddress", "language_dependent":false },{ "name":"assetvehiclemake", "sequence":30, "data_item":"defassetvehiclemake", "language_dependent":false },{ "name":"assetvehiclereg", "sequence":32, "data_item":"defassetvehiclereg", "language_dependent":false },{ "name":"offences", "sequence":100, "data_item":"accountoffpen", "language_dependent":false },{ "name":"gobterminalentries", "sequence":105, "data_item":"resultentries", "language_dependent":false },{ "name":"gobcontractor", "sequence":110, "data_item":"enforcerdetail", "language_dependent":false }]',NULL),
('CLAMPOC','CLAC','EN',0,'EO','LJA','44_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"moneyowed", "sequence":15, "data_item":"accountbalance", "language_dependent":false },{ "name":"contractoraddress", "sequence":25, "data_item":"procaddress", "language_dependent":false },{ "name":"assetvehiclemake", "sequence":30, "data_item":"defassetvehiclemake", "language_dependent":false },{ "name":"assetvehiclereg", "sequence":35, "data_item":"defassetvehiclereg", "language_dependent":false },{ "name":"offences", "sequence":100, "data_item":"accountoffpen", "language_dependent":false },{ "name":"gobterminalentries", "sequence":105, "data_item":"resultentries", "language_dependent":false },{ "name":"gobcontractor", "sequence":110, "data_item":"enforcerdetail", "language_dependent":false }]',NULL),
('COMMWT','DEF','EN',0,'A',NULL,'43_0','[{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"moneyowed", "sequence":22, "data_item":"accountbalance", "language_dependent":false },{ "name":"offences", "sequence":100, "data_item":"accountoffpen", "language_dependent":false },{ "name":"terminalentries", "sequence":105, "data_item":"resultentries", "language_dependent":false }]',NULL),
('COMMWTP','DEF','EN',0,'A',NULL,'43_0','[{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"moneyowedcase", "sequence":26, "data_item":"accountbalance", "language_dependent":false },{ "name":"goboffences", "sequence":105, "data_item":"accountoffpen", "language_dependent":false },{ "name":"terminalentries", "sequence":110, "data_item":"resultentries", "language_dependent":false },{ "name":"gobenforcer", "sequence":120, "data_item":"enforcerdetail", "language_dependent":false },{ "name":"accnomde", "sequence":125, "data_item":"caseaccnomde", "language_dependent":false },{ "name":"resultcode", "sequence":130, "data_item":"resultcode", "language_dependent":false }]',NULL),
('COMPLETT','CRED','EN',0,'A','Area','46_0','[{ "name":"creddetails", "sequence":5, "data_item":"creddetail", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"compdetail", "language_dependent":false },{ "name":"aauaddress", "sequence":25, "data_item":"accountenfaauaddr", "language_dependent":false },{ "name":"defaddress", "sequence":30, "data_item":"defaddress", "language_dependent":false }]',NULL),
('CONSOL','DEF','EN',0,'A','Area','46_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"consoldetail", "sequence":15, "data_item":"consoldetail", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false },{ "name":"timetopay", "sequence":30, "data_item":"casepaymentterms_rt", "language_dependent":false }]',NULL),
('CTPAYSF','DEF','EN',0,'A','Area','20_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"transferslips", "sequence":20, "data_item":"transferslips", "language_dependent":false }]',NULL),
('DWAR','DEF','EN',0,'EO',NULL,'31_0','[{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"offences", "sequence":30, "data_item":"accountoffpen", "language_dependent":false },{ "name":"procserver", "sequence":35, "data_item":"enforcerdetail", "language_dependent":false }]',NULL),
('ENFSUM','DEF','EN',0,'EO','Area','46_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":15, "data_item":"accountbalance", "language_dependent":false },{ "name":"prisondetention", "sequence":50, "data_item":"caseprisondetention", "language_dependent":false },{ "name":"ninumber", "sequence":55, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"offences", "sequence":100, "data_item":"accountoffpen", "language_dependent":false },{ "name":"gobcasedetails", "sequence":105, "data_item":"casedetail", "language_dependent":false },{ "name":"gobterminalentries", "sequence":110, "data_item":"resultentries", "language_dependent":false },{ "name":"hometelno", "sequence":115, "data_item":"defhometelno", "language_dependent":false },{ "name":"mobtelno", "sequence":120, "data_item":"defmobtelno", "language_dependent":false },{ "name":"defemails", "sequence":125, "data_item":"defemailnum", "language_dependent":false },{ "name":"mc100", "sequence":130, "data_item":"casemc100form", "language_dependent":false }]',NULL),
('ENFWTB','DEF','EN',0,'EO',NULL,'33_0','[{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"bailamount", "sequence":30, "data_item":"accountbailamount", "language_dependent":false },{ "name":"offences", "sequence":65, "data_item":"accountoffpen", "language_dependent":false },{ "name":"ninumber", "sequence":70, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"hometelno", "sequence":80, "data_item":"defhometelno", "language_dependent":false },{ "name":"businesstelno", "sequence":85, "data_item":"defphone", "language_dependent":false },{ "name":"mobtelno", "sequence":90, "data_item":"defmobtelno", "language_dependent":false },{ "name":"defendantemail", "sequence":95, "data_item":"defemailnum", "language_dependent":false },{ "name":"assetvehiclereg", "sequence":100, "data_item":"defassetvehiclereg", "language_dependent":false },{ "name":"assetvehiclemake", "sequence":105, "data_item":"defassetvehiclemake", "language_dependent":false },{ "name":"defendantalias", "sequence":110, "data_item":"defaliasesnum", "language_dependent":false },{ "name":"accountnotes", "sequence":115, "data_item":"accountnotes", "language_dependent":false },{ "name":"gobenforcerdetail", "sequence":120, "data_item":"enforcerdetail", "language_dependent":false },{ "name":"gobcasedetail", "sequence":125, "data_item":"casedetail", "language_dependent":false }]',NULL),
('ENFWTN','DEF','EN',0,'EO',NULL,'31_0','[{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"offences", "sequence":50, "data_item":"accountoffpen", "language_dependent":false },{ "name":"ninumber", "sequence":70, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"hometelno", "sequence":80, "data_item":"defhometelno", "language_dependent":false },{ "name":"businesstelno", "sequence":85, "data_item":"defphone", "language_dependent":false },{ "name":"mobtelno", "sequence":90, "data_item":"defmobtelno", "language_dependent":false },{ "name":"defendantemail", "sequence":95, "data_item":"defemailnum", "language_dependent":false },{ "name":"assetvehiclereg", "sequence":100, "data_item":"defassetvehiclereg", "language_dependent":false },{ "name":"assetvehiclemake", "sequence":105, "data_item":"defassetvehiclemake", "language_dependent":false },{ "name":"defendantalias", "sequence":110, "data_item":"defaliasesnum", "language_dependent":false },{ "name":"accountnotes", "sequence":115, "data_item":"accountnotes", "language_dependent":false },{ "name":"gobenforcer", "sequence":120, "data_item":"enforcerdetail", "language_dependent":false },{ "name":"terminalentries", "sequence":130, "data_item":"resultentries", "language_dependent":false }]',NULL),
('ENFWTU','DEF','EN',0,'EO',NULL,'33_0','[{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"bailamount", "sequence":30, "data_item":"accountbailamount", "language_dependent":false },{ "name":"baildirection", "sequence":40, "data_item":"courtbdfine", "language_dependent":false },{ "name":"offences", "sequence":65, "data_item":"accountoffpen", "language_dependent":false },{ "name":"ninumber", "sequence":70, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"hometelno", "sequence":80, "data_item":"defhometelno", "language_dependent":false },{ "name":"businesstelno", "sequence":85, "data_item":"defphone", "language_dependent":false },{ "name":"mobtelno", "sequence":90, "data_item":"defmobtelno", "language_dependent":false },{ "name":"defendantemail", "sequence":95, "data_item":"defemailnum", "language_dependent":false },{ "name":"assetvehiclereg", "sequence":100, "data_item":"defassetvehiclereg", "language_dependent":false },{ "name":"assetvehiclemake", "sequence":105, "data_item":"defassetvehiclemake", "language_dependent":false },{ "name":"defendantalias", "sequence":110, "data_item":"defaliasesnum", "language_dependent":false },{ "name":"accountnotes", "sequence":115, "data_item":"accountnotes", "language_dependent":false },{ "name":"gobcasedetails", "sequence":125, "data_item":"casedetail", "language_dependent":false },{ "name":"gobprocessserver", "sequence":130, "data_item":"enforcerdetail", "language_dependent":false },{ "name":"terminalentries", "sequence":135, "data_item":"resultentries", "language_dependent":false }]',NULL),
('ESCFNOT','DEF','EN',0,'A','Area','20_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false },{ "name":"timetopay", "sequence":25, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"terminalentries", "sequence":30, "data_item":"resultentries", "language_dependent":false }]',NULL),
('ESCISS','DEF','EN',0,'EO','Area','45_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"datesuspcommittal", "sequence":15, "data_item":"accountdatesuspcom", "language_dependent":false },{ "name":"terms", "sequence":20, "data_item":"accountttp", "language_dependent":false },{ "name":"sumdue", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"returnaddress", "sequence":60, "data_item":"adjcmuaddress", "language_dependent":false },{ "name":"gobcasedetails", "sequence":65, "data_item":"casedetail", "language_dependent":false },{ "name":"finesofficeaddress", "sequence":70, "data_item":"accountenfaauaddr", "language_dependent":false }]',NULL),
('FCOLLO','DEF','EN',0,'EO','LJA','45_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false },{ "name":"timetopay", "sequence":50, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"terminalentries", "sequence":60, "data_item":"resultentries", "language_dependent":false }]',NULL),
('FFSN','DEF','EN',0,'A',NULL,'45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"accountbalance", "sequence":2, "data_item":"accountbalance", "language_dependent":false }]',NULL),
('FINOR','DEF','EN',0,'AP','LJA','45_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"timetopay", "sequence":10, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"offences", "sequence":15, "data_item":"accountoffpen", "language_dependent":false },{ "name":"collorder", "sequence":20, "data_item":"collectionorder", "language_dependent":false }]',NULL),
('FINOT','DEF','EN',0,'A','Area','45_0','[{ "name":"tfoindetails", "sequence":5, "data_item":"tfoindetail", "language_dependent":false },{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"offences", "sequence":15, "data_item":"accountoffpen", "language_dependent":false },{ "name":"timetopay", "sequence":20, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"totalamount", "sequence":25, "data_item":"accountbalance", "language_dependent":false }]',NULL),
('FINOTA','DEF','EN',0,'A','Area','40_0','[{ "name":"transferdetails", "sequence":5, "data_item":"tfoackdetail", "language_dependent":false },{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false }]',NULL),
('FINREMB','DEF','EN',0,'A','Area','45_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"accountbalance", "sequence":15, "data_item":"accountbalance", "language_dependent":false }]',NULL),
('FREGNR','FRA','EN',0,NULL,NULL,'12_0','[{ "name":"ljaimposing", "sequence":5, "data_item":"courtimposing", "language_dependent":false },{ "name":"defendantalias", "sequence":10, "data_item":"defaliasesnum", "language_dependent":false },{ "name":"defendantaddress", "sequence":20, "data_item":"defaddress", "language_dependent":false },{ "name":"accountbalance", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"dateimposed", "sequence":30, "data_item":"accountdateimposed", "language_dependent":false }]',NULL),
('FSO','DEF','EN',0,'EO','LJA','43_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"balanceoutstanding", "sequence":2, "data_item":"accountbalance", "language_dependent":false },{ "name":"gobttp", "sequence":4, "data_item":"accountttp", "language_dependent":false },{ "name":"prisondetention", "sequence":5, "data_item":"caseprisondetention", "language_dependent":false },{ "name":"offences", "sequence":6, "data_item":"accountoffpen", "language_dependent":false },{ "name":"terminalentries", "sequence":7, "data_item":"resultentries", "language_dependent":false },{ "name":"casettp", "sequence":10, "data_item":"casepaymentterms_rt", "language_dependent":false }]',NULL),
('SUSNOT','DEF','EN',0,'A','LJA','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"offences", "sequence":2, "data_item":"casefullresult", "language_dependent":false },{ "name":"terminalentries", "sequence":10, "data_item":"resultentries", "language_dependent":false },{ "name":"goboffences", "sequence":15, "data_item":"accountoffpen", "language_dependent":false },{ "name":"prisondetention", "sequence":40, "data_item":"caseprisondetention", "language_dependent":false },{ "name":"gobdefage", "sequence":50, "data_item":"defage", "language_dependent":false }]',NULL),
('TFOAR','OTHC','EN',0,'A','Area','20_0','[{ "name":"tfooutdetail", "sequence":5, "data_item":"tfooutdetail", "language_dependent":false },{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false }]',NULL),
('TFOOUT','DEF','EN',0,'A','Area','26_0','[{ "name":"receivingdivision", "sequence":1, "data_item":"recipaddress", "language_dependent":false },{ "name":"terms", "sequence":2, "data_item":"accountttp", "language_dependent":false },{ "name":"sendingdevisionaddress", "sequence":3, "data_item":"sessionpsaaddress", "language_dependent":false },{ "name":"debtorname", "sequence":6, "data_item":"accountname", "language_dependent":false },{ "name":"debtoraddress", "sequence":8, "data_item":"defaddress", "language_dependent":false },{ "name":"accountdetails", "sequence":10, "data_item":"accounthistory", "language_dependent":false },{ "name":"gobtfooutdetail", "sequence":20, "data_item":"tfooutdetail", "language_dependent":false },{ "name":"language", "sequence":25, "data_item":"accountlang", "language_dependent":false }]',NULL),
('TTPLET','DEF','EN',0,'A','Area','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"balance", "sequence":10, "data_item":"accountbalance", "language_dependent":false },{ "name":"timetopay", "sequence":20, "data_item":"casepaymentterms", "language_dependent":false }]',NULL),
('UNPRELET','CRED','EN',0,'A','Area','20_0','[{ "name":"chequedetails", "sequence":5, "data_item":"chequedetail", "language_dependent":false }]',NULL),
('UPWO','DEF','EN',0,'EO','LJA','20_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"amountoffines", "sequence":17, "data_item":"accountfoutstanding", "language_dependent":false },{ "name":"gobterminalentries", "sequence":40, "data_item":"resultentries", "language_dependent":false }]',NULL),
('CY_ABDD','DEF','CY',0,'EO','Area','26_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"ninumber", "sequence":10, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"amountoutstanding", "sequence":15, "data_item":"accountbalance", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false }]',NULL),
('CY_AEOFD','DEF','CY',0,'EO','Area','45_0','[{ "name":"employeeaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"ninumber", "sequence":15, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"totaloutstanding", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"gobterminalentires", "sequence":30, "data_item":"resultentries", "language_dependent":false },{ "name":"webempdet", "sequence":35, "data_item":"caseemploymentdets", "language_dependent":false },{ "name":"gobempdet", "sequence":40, "data_item":"accountemploydets", "language_dependent":false }]',NULL),
('CY_BACKLET','DEF','CY',1,'EO','Area','45_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"warrantnumber", "sequence":10, "data_item":"accountwarrantno", "language_dependent":false },{ "name":"amountenforced", "sequence":15, "data_item":"accountbalance", "language_dependent":false },{ "name":"warrantcontactdetails", "sequence":20, "data_item":"accountwarrantcont", "language_dependent":false }]',NULL),
('CY_BACKLETDW','DEF','CY',2,'EO','Area','45_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":10, "data_item":"accountbalance", "language_dependent":false },{ "name":"dwdays", "sequence":15, "data_item":"ctdwdays", "language_dependent":false }]',NULL),
('CY_COMPLETT','CRED','CY',0,'A','Area','46_0','[{ "name":"creditordetail", "sequence":5, "data_item":"creddetail", "language_dependent":false },{ "name":"defendantname", "sequence":15, "data_item":"accountname", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"compdetail", "language_dependent":false },{ "name":"enfaauaddress", "sequence":25, "data_item":"accountenfaauaddr", "language_dependent":false },{ "name":"defaddress", "sequence":30, "data_item":"defaddress", "language_dependent":false }]',NULL),
('CY_CONSOL','DEF','CY',0,'A','Area','46_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"consoldetails", "sequence":15, "data_item":"consoldetail", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false },{ "name":"timetopay", "sequence":30, "data_item":"casepaymentterms_rt", "language_dependent":false }]',NULL),
('CY_ENFSUM','DEF','CY',0,'EO','Area','46_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"amountenforced", "sequence":10, "data_item":"accountbalance", "language_dependent":false },{ "name":"prisondetention", "sequence":45, "data_item":"caseprisondetention", "language_dependent":false },{ "name":"offences", "sequence":50, "data_item":"accountoffpen", "language_dependent":false },{ "name":"ninumber", "sequence":55, "data_item":"defnatinsnum", "language_dependent":false },{ "name":"gobcasedetails", "sequence":60, "data_item":"casedetail", "language_dependent":false },{ "name":"gobterminalentries", "sequence":65, "data_item":"resultentries", "language_dependent":false },{ "name":"defemails", "sequence":70, "data_item":"defemailnum", "language_dependent":false },{ "name":"mc100", "sequence":75, "data_item":"casemc100form", "language_dependent":false }]',NULL),
('CY_ESCISS','DEF','CY',0,'EO','Area','45_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"datesuspcommittal", "sequence":15, "data_item":"accountdatesuspcom", "language_dependent":false },{ "name":"terms", "sequence":20, "data_item":"accountttp", "language_dependent":false },{ "name":"sumdue", "sequence":25, "data_item":"accountbalance", "language_dependent":false },{ "name":"returnaddress", "sequence":60, "data_item":"adjcmuaddress", "language_dependent":false },{ "name":"gobcasedetails", "sequence":65, "data_item":"casedetail", "language_dependent":false },{ "name":"finesofficeaddress", "sequence":70, "data_item":"accountenfaauaddr", "language_dependent":false }]',NULL),
('CY_FCOLLO','DEF','CY',0,'EO','LJA','45_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"offences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false },{ "name":"timetopay", "sequence":50, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"terminalentries", "sequence":60, "data_item":"resultentries", "language_dependent":false }]',NULL),
('CY_FFSN','DEF','CY',0,'A',NULL,'45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"accountbalance", "sequence":2, "data_item":"accountbalance", "language_dependent":false }]',NULL),
('CY_FINOR','DEF','CY',0,'AP','LJA','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"timetopay", "sequence":2, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"offences", "sequence":3, "data_item":"accountoffpen", "language_dependent":false },{ "name":"collorder", "sequence":4, "data_item":"collectionorder", "language_dependent":false }]',NULL),
('CY_FINOT','DEF','CY',0,'A','Area','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"timetopay", "sequence":2, "data_item":"casepaymentterms_rt", "language_dependent":false },{ "name":"offences", "sequence":3, "data_item":"accountoffpen", "language_dependent":false },{ "name":"collorder", "sequence":4, "data_item":"collectionorder", "language_dependent":false },{ "name":"tfodetails", "sequence":5, "data_item":"tfoindetail", "language_dependent":false },{ "name":"totalamount", "sequence":10, "data_item":"accountbalance", "language_dependent":false }]',NULL),
('CY_FINREMB','DEF','CY',0,'A','Area','45_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"accountbalance", "sequence":10, "data_item":"accountbalance", "language_dependent":false }]',NULL),
('CY_SUSNOT','DEF','CY',0,'A','LJA','45_0','[{ "name":"defendantaddress", "sequence":5, "data_item":"defaddress", "language_dependent":false },{ "name":"offences", "sequence":10, "data_item":"casefullresult", "language_dependent":false },{ "name":"terminalentries", "sequence":15, "data_item":"resultentries", "language_dependent":false },{ "name":"goboffences", "sequence":20, "data_item":"accountoffpen", "language_dependent":false },{ "name":"prisondetention", "sequence":45, "data_item":"caseprisondetention", "language_dependent":false },{ "name":"gobdefage", "sequence":55, "data_item":"defage", "language_dependent":false }]',NULL),
('CY_TTPLET','DEF','CY',0,'A','Area','45_0','[{ "name":"defendantaddress", "sequence":1, "data_item":"defaddress", "language_dependent":false },{ "name":"balance", "sequence":5, "data_item":"accountbalance", "language_dependent":false },{ "name":"timetopay", "sequence":10, "data_item":"casepaymentterms", "language_dependent":false }]',NULL),
('CY_UPWO','DEF','CY',0,'EO','LJA','28_0','[{ "name":"defendantaddress", "sequence":10, "data_item":"defaddress", "language_dependent":false },{ "name":"amountoffines", "sequence":17, "data_item":"accountfoutstanding", "language_dependent":false },{ "name":"gobresultentries", "sequence":40, "data_item":"resultentries", "language_dependent":false }]',NULL);
