/**
 * OPAL Program
 *
 * MODULE      : create_view_v_suspense_item_summary.sql
 *
 * DESCRIPTION : Creates the v_suspense_item_summary view.
 *
 *               The view provides the summary information required when
 *               searching for and opening the View Suspense Item screen.
 *
 *               The view intentionally contains NO WHERE clause.
 *               JPA/Hibernate will filter the view using:
 *
 *                   business_unit_id
 *                   suspense_item_number
 *
 * TABLES:
 *
 *   suspense_items
 *       Main source of suspense item information.
 *
 *   suspense_accounts
 *       Used to identify the business unit associated with the
 *       suspense item.
 *
 *   business_units
 *       Provides the business unit name.
 *
 *   suspense_item_number_index
 *       Holds the unique business_unit_id / suspense_item_number
 *       combinations generated by Opal.
 *
 *       This is deliberately a LEFT JOIN because legacy GOB suspense
 *       items may not have a corresponding index record.
 *
 *   suspense_transactions
 *       Used to calculate the current suspense item balance.
 *
 * BALANCE:
 *
 *   Balance is calculated as the SUM of all suspense transaction amounts
 *   associated with the suspense item.
 *
 *   Positive and negative values are summed naturally.
 *
 *   Where:
 *       - no transactions exist, or
 *       - transaction amounts sum to zero
 *
 *   the balance returned is 0.00.
 *
 * OUTPUT:
 *
 *   suspense_item_id
 *   suspense_item_number
 *   business_unit_id
 *   business_unit_name
 *   created_date
 *   suspense_item_type
 *   balance
 *
 * NOTES:
 *
 *   suspense_item_type is an enum on suspense_items and is exposed as
 *   TEXT by this view.
 *
 *   No "details" column is returned because it is explicitly outside
 *   the scope of this view.
 * 
 * 
 * VERSION HISTORY:
*
* Date          Author      Version     Nature of Change
* ----------    -------     --------    ------------------------------------------------------------------------
* 17/08/2026    I Chandio       1.0    PO-10191 DB - Fines - Create database view for Suspense 1 - Search and View item - v_suspense_item_summary
 * 
 * 
 */

CREATE OR REPLACE VIEW public.v_suspense_item_summary AS
SELECT
    si.suspense_item_id,
    si.suspense_item_number,
    sa.business_unit_id,
    bu.business_unit_name,
    si.created_date,
    si.suspense_item_type,
    COALESCE(st_bal.balance, 0.00::NUMERIC) AS balance
FROM public.suspense_items si
JOIN public.suspense_accounts sa
    ON sa.suspense_account_id = si.suspense_account_id
JOIN public.business_units bu
    ON bu.business_unit_id = sa.business_unit_id
LEFT JOIN public.suspense_item_number_index sini
    ON sini.suspense_item_number = si.suspense_item_number
   AND sini.business_unit_id = sa.business_unit_id
LEFT JOIN (
    SELECT
        suspense_item_id,
        SUM(amount) AS balance
    FROM public.suspense_transactions
    GROUP BY suspense_item_id
) st_bal
    ON st_bal.suspense_item_id = si.suspense_item_id;